Update Git repository using egup-single

diff --git a/support/install b/support/install
--- a/support/install
+++ b/support/install
@@ -6,7 +6,7 @@ source ember_bash_setup &> /dev/null
 #NOTE: MAINTENANCE: Manual error printing
 if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
     printf '%b' '\033[1;31m' >&2
-    echo "ERROR: ember-shared is not properly installed! It must be installed before installing Crystallize." >&2
+    echo "ERROR: ember-shared is not properly installed! It must be installed before installing eite." >&2
     printf '%b' '\033[0m' >&2
     exit 1
 fi
@@ -19,79 +19,100 @@ if [[ "$1" == "--skip-config-file" ]]; then
     shift
 fi
 
+overrideInstalledAppDataDir="/usr/share"
+overrideInstalledAppDataDirArg="${1#*=}"
+if [[ "$1" == "--override-data-dir="* ]] && [[ -n "$overrideInstalledAppDataDirArg" ]]; then
+    overrideInstalledAppDataDir="$overrideInstalledAppDataDirArg"
+fi
+shift
+
+emberPrefix="$(<support/.prefix)" || true
+emberMandir="$(<support/.mandir)" || true
+emberInfodir="$(<support/.infodir)" || true
+emberDatadir="$(<support/.datadir)" || true
+emberSysconfdir="$(<support/.sysconfdir)" || true
+emberLocalstatedir="$(<support/.localstatedir)" || true
+
 #echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
-if [[ -n "$1" ]]; then
-    crystallizeDestdir="$1"
+if [[ -z "$emberDestdir" ]] && [[ -n "$1" ]]; then
+    emberDestdir="$1"
     shift
 fi
-if [[ "$1" == "--skip-config-file" ]]; then
-    skipConfigFile="true"
+if [[ -z "$emberPrefix" ]] && [[ -n "$1" ]]; then
+    emberPrefix="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizePrefix="$1"
+if [[ -z "$emberCapPrefix" ]] && [[ -n "$1" ]]; then
+    emberCapPrefix="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizeCapPrefix="$1"
+if [[ -z "$emberExecPrefix" ]] && [[ -n "$1" ]]; then
+    emberExecPrefix="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizeExecPrefix="$1"
+if [[ -z "$emberBindir" ]] && [[ -n "$1" ]]; then
+    emberBindir="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizeBindir="$1"
+if [[ -z "$emberDatarootdir" ]] && [[ -n "$1" ]]; then
+    emberDatarootdir="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizeDatarootdir="$1"
+if [[ -z "$emberDatadir" ]] && [[ -n "$1" ]]; then
+    emberDatadir="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizeDatadir="$1"
+if [[ -z "$emberSysconfdir" ]] && [[ -n "$1" ]]; then
+    emberSysconfdir="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizeSysconfdir="$1"
+if [[ -z "$emberSharedstatedir" ]] && [[ -n "$1" ]]; then
+    emberSharedstatedir="$1"
     shift
 fi
-if [[ -n "$1" ]]; then
-    crystallizeSharedstatedir="$1"
-    shift
-fi
-if ! [[ -n "$crystallizePrefix" ]]; then
-    if ! [[ -n "$crystallizeCapPrefix" ]]; then
-        crystallizePrefix="$crystallizeDestdir"/usr/local
+if [[ -z "$emberPrefix" ]]; then
+    if [[ -z "$emberCapPrefix" ]]; then
+        emberPrefix=/usr/local
     else
-        crystallizePrefix="$crystallizeCapPrefix"
+        emberPrefix="$emberCapPrefix"
     fi
 fi
-#echo "crystallizePrefix: $crystallizePrefix"
-if ! [[ -n "$crystallizeExecPrefix" ]]; then
-    crystallizeExecPrefix="$crystallizePrefix"
+emberPrefix="$emberDestdir$emberPrefix"
+#echo "emberPrefix: $emberPrefix"
+if [[ -z "$emberExecPrefix" ]]; then
+    emberExecPrefix="$emberPrefix"
+else
+    emberExecPrefix="$emberDestdir$emberExecPrefix"
 fi
-#echo "crystallizeExecPrefix: $crystallizeExecPrefix"
-if ! [[ -n "$crystallizeBindir" ]]; then
-    crystallizeBindir="$crystallizeExecPrefix"/bin
+#echo "emberExecPrefix: $emberExecPrefix"
+if [[ -z "$emberBindir" ]]; then
+    emberBindir="$emberExecPrefix"/bin
 fi
-#echo "crystallizeBindir: $crystallizeBindir"
-if ! [[ -n "$crystallizeDatarootdir" ]]; then
-    crystallizeDatarootdir="$crystallizePrefix"/share
+#echo "emberBindir: $emberBindir"
+if [[ -z "$emberDatarootdir" ]]; then
+    emberDatarootdir="$emberPrefix"/share
 fi
-#echo "crystallizeDatarootdir: $crystallizeDatarootdir"
-if ! [[ -n "$crystallizeDatadir" ]]; then
-    crystallizeDatadir="$crystallizeDatarootdir"
+#echo "emberDatarootdir: $emberDatarootdir"
+if [[ -z "$emberDatadir" ]]; then
+    emberDatadir="$emberDestdir$emberDatarootdir"
+else
+    emberDatadir="$emberDestdir$emberDatadir"
 fi
-#echo "crystallizeDatadir: $crystallizeDatadir"
-if ! [[ -n "$crystallizeSysconfdir" ]]; then
-    crystallizeSysconfdir="$crystallizePrefix"/etc
+#echo "emberDatadir: $emberDatadir"
+if [[ -z "$emberSysconfdir" ]]; then
+    emberSysconfdir="$emberPrefix"/etc
+else
+    emberSysconfdir="$emberPrefix$emberSysconfdir"
 fi
-#echo "crystallizeSysconfdir: $crystallizeSysconfdir"
-if ! [[ -n "$crystallizeSharedstatedir" ]]; then
-    crystallizeSharedstatedir="$crystallizePrefix"/var
+#echo "emberSysconfdir: $emberSysconfdir"
+if [[ -z "$emberSharedstatedir" ]]; then
+    emberSharedstatedir="$emberPrefix"/var
+else
+    emberSharedstatedir="$emberPrefix$emberSharedstatedir"
 fi
-#echo "crystallizeSharedstatedir: $crystallizeSharedstatedir"
+#echo "emberSharedstatedir: $emberSharedstatedir"
+
+#### End of Makefile install script template ####
 
 crystallizeEmberdir="$crystallizePrefix"/Ember\ Library
 
