Update Ember tree

diff --git a/support/install b/support/install
--- a/support/install
+++ b/support/install
@@ -3,8 +3,12 @@
 source ember_bash_setup &> /dev/null
 
 #NOTE: MAINTENANCE: Manual error printing
-trap 'printf '\''%b'\'' '\''\033[1;31m'\'' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1' ERR
-if [[ -z "$(ember-getconf emberSharedVersion)" ]] || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)." >&2; printf '\''%b'\'' '\''\033[0m'\'' >&2; exit 1; }
+if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
+    printf '%b' '\033[1;31m' >&2
+    echo "ERROR: ember-shared is not properly installed! It must be installed before installing Crystallize." >&2
+    printf '%b' '\033[0m' >&2
+    exit 1
+fi
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
 # set -x
