Update Ember tree

diff --git a/scripts/crystallize-bash_setup b/scripts/crystallize-bash_setup
--- a/scripts/crystallize-bash_setup
+++ b/scripts/crystallize-bash_setup
@@ -30,7 +30,7 @@ git-escape-path() {
 
 # Function is defined with parentheses to make it run in a subshell to prevent the "die" affecting the calling script (the calling script should be responsible for trapping/handling nonzero exit codes itself)
 sregi_available_by_hash() (
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
     local sregDir=""
     if [[ "$1" == "--sreg-dir" ]]; then
@@ -63,7 +63,7 @@ sregi_available_by_hash() (
 
 # Function is defined with parentheses to avoid dumping the enclosed function definition into the calling script
 sregi_hash_from_file() (
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
     file="$1"
     sregi_hash_from_file_pipecheck() {
diff --git a/scripts/sreg_build_backup_set b/scripts/sreg_build_backup_set
--- a/scripts/sreg_build_backup_set
+++ b/scripts/sreg_build_backup_set
@@ -11,7 +11,7 @@ finish() {
 }
 trap finish EXIT
 
-trap 'finish; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+trap 'finish; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
 sregDir=""
 if [[ "$1" == "--sreg-dir" ]]; then
diff --git a/scripts/sreg_flush_localstore b/scripts/sreg_flush_localstore
--- a/scripts/sreg_flush_localstore
+++ b/scripts/sreg_flush_localstore
@@ -23,7 +23,7 @@ finish() {
         fi
     fi
 }
-trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."; rm -f "${dbDir:?}"/.LocalStore.lock; finish; exit 1' ERR
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; rm -f "${dbDir:?}"/.LocalStore.lock; finish; exit 1' ERR
 
 finishExit() {
     save_traps="$(trap)"
diff --git a/scripts/sreg_folder_check b/scripts/sreg_folder_check
--- a/scripts/sreg_folder_check
+++ b/scripts/sreg_folder_check
@@ -25,9 +25,9 @@ finish() {
     if [[ -e "/tmp/${fsckId:?}" ]]; then
         rm -r "/tmp/${fsckId:?}"
     fi
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate) while finishing sreg_folder_check."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate) while finishing sreg_folder_check."' ERR
 }
-trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."; finish; exit 1' ERR
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; finish; exit 1' ERR
 trap finish EXIT
 
 sregVerify=""
diff --git a/scripts/sregi_copy_write b/scripts/sregi_copy_write
--- a/scripts/sregi_copy_write
+++ b/scripts/sregi_copy_write
@@ -31,9 +31,9 @@ finish() {
         fi
     fi
     )
-    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate) while finishing sregi_copy_write."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate) while finishing sregi_copy_write."' ERR
 }
-trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."; finish; exit 1' ERR
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; finish; exit 1' ERR
 trap finish EXIT
 
 sregDir=""
@@ -91,7 +91,7 @@ if [[ -f "$destinationName" ]]; then
     destinationChecksum=""
     hasEncounteredError="0"
     if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
-        trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."; hasEncounteredError="1"' ERR
+        trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; hasEncounteredError="1"' ERR
         assumePointerDbEntryFileExists="true"
         if [[ "$sregNoVerify" == "true" ]]; then
             destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
@@ -134,7 +134,7 @@ if [[ -f "$destinationName" ]]; then
         fi
     fi
 fi
-trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 crystalWorkdir="$(crystallize-getconf WorkDirectory)"
 streamId="sreg-$(date-uuid)"
 crystalSubdir="$crystalWorkdir/$streamId"
diff --git a/scripts/sregi_get_length_from_pointer b/scripts/sregi_get_length_from_pointer
--- a/scripts/sregi_get_length_from_pointer
+++ b/scripts/sregi_get_length_from_pointer
@@ -5,7 +5,7 @@ source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
 
-trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
 sregDir=""
 if [[ "$1" == "--sreg-dir" ]]; then
@@ -31,7 +31,7 @@ if [[ -f "$pointer" ]] && [[ ! -h "$pointer" ]]; then
         if ! [[ -e "$pointer.length" ]]; then
             crystalWorkdir="$(crystallize-getconf WorkDirectory)"
             streamId="sregi_get_length_from_pointer-$(date-uuid)"
-            trap 'rm -f ${streamId:?}; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+            trap 'rm -f ${streamId:?}; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
             sreg_read_stream --sreg-dir "$sregDir" < "$pointer" > "$crystalWorkdir/.$streamId"
             retrievedSize="$(stat --printf='%s\n' "$crystalWorkdir/.$streamId")"
             echo "$crystalWorkdir/.$streamId (not hash pointer) has length $retrievedSize bytes. Pointer contents: $(xxd "$pointer")"
@@ -49,7 +49,7 @@ if [[ -f "$pointer" ]] && [[ ! -h "$pointer" ]]; then
             # This case can be removed once/if there aren't any pointers that need to be read that have only 2 lines.
             crystalWorkdir="$(crystallize-getconf WorkDirectory)"
             streamId="sregi_get_size_from_pointer-$(date-uuid)"
-            trap 'rm -f ${streamId:?}; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+            trap 'rm -f ${streamId:?}; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
             sreg_read_stream --sreg-dir "$sregDir" < "$pointer" > "$crystalWorkdir/.$streamId"
             retrievedSize="$(stat --printf='%s\n' "$crystalWorkdir/.$streamId")"
             echo "$crystalWorkdir/.$streamId has length $retrievedSize bytes. Pointer contents: $(<"$pointer")"
diff --git a/scripts/sregi_hashpointer_sane b/scripts/sregi_hashpointer_sane
--- a/scripts/sregi_hashpointer_sane
+++ b/scripts/sregi_hashpointer_sane
@@ -4,7 +4,7 @@ source ember_bash_setup &> /dev/null
 #set -x
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
 success() {
     exit 0
@@ -83,7 +83,7 @@ then
             if ! sreg_read_stream --sreg-dir "$sregDir" --checksum "$knownChecksum" --skip-cache < "$inputFile" > /dev/null; then
                 trap - ERR
                 mv "$2" "$2.CORRUPTED-HASHPOINTER"
-                trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} at $(emdate)."' ERR
+                trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
                 die "Item $inputFile did not match the stored checksum!"
             fi
         else
