Update Ember tree

diff --git a/scripts/crystallize-logsession b/scripts/crystallize-logsession
--- a/scripts/crystallize-logsession
+++ b/scripts/crystallize-logsession
@@ -118,20 +118,9 @@ hashdeep -c md5,sha1,sha256,tiger,whirlpool -o fbsd -r "$crystalWorkdir/""$Cryst
 
 mkfifo "$crystalWorkdir/$CrystalID.pax"
 
-#Ignore exit code 1 from tar on Linux, which indicates files changed while reading; see http://stackoverflow.com/questions/20318852/tar-file-changed-as-we-read-it
-set +e
-tar -cv -P -S --format pax -f "$crystalWorkdir/$CrystalID.pax" "$crystalWorkdir/""$CrystallizeFirstArg" "${CrystallizePaths[@]}" "$crystalWorkdir/$CrystalID" "$crystalWorkdir/$CrystalID.local.idx" "$crystalWorkdir/$CrystalID.deep.idx" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.time-start.warc.gz" "$crystalWorkdir/$CrystalID.ip.warc.gz" "$crystalWorkdir/$CrystalID.time-env.warc.gz"
-exitcode=$?
-
-if [ "$exitcode" != "0" ] && [[ $OSTYPE != *inux* ]]; then
-    exit $exitcode
-fi
-if [ "$exitcode" != "1" ] && [ "$exitcode" != "0" ]; then
-    exit $exitcode
-fi
-set -e
-
-echo "Successfully tared!"
+tar -cv -P -S --format pax -f "$crystalWorkdir/$CrystalID.pax" "$crystalWorkdir/""$CrystallizeFirstArg" "${CrystallizePaths[@]}" "$crystalWorkdir/$CrystalID" "$crystalWorkdir/$CrystalID.local.idx" "$crystalWorkdir/$CrystalID.deep.idx" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.time-start.warc.gz" "$crystalWorkdir/$CrystalID.ip.warc.gz" "$crystalWorkdir/$CrystalID.time-env.warc.gz" &
+tarpid="$!"
+sleep 1
 
 unset opt
 unset optb
@@ -144,27 +133,49 @@ set -e
 
 #If the opt(b) variable is unset, insert the text after "opt(b)+"
 #opt is for GNU/Linux; optb is for others
-script ${optb+/dev/null} ${opt+-e} ${opt+-c} crystallize-internal-xz ${opt+/dev/null}
-
-rm -v "$crystalWorkdir/$CrystalID".pax
+script ${optb+/dev/null} ${opt+-e} ${opt+-c} crystallize-internal-xz ${opt+/dev/null} &
+sleep 1
 
 mkfifo "$crystalWorkdir/$CrystalID".pax.xz.gpg
 
-gpg --yes -c -v --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID".pax.xz
-
-rm -v "$crystalWorkdir/$CrystalID".pax.xz
-
-mv "$crystalWorkdir/$CrystalID".pax.xz.gpg "$crystalWorkdir/$CrystalID".coal5
+gpg --yes -c -v --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID".pax.xz &
+sleep 1
 
 echo "Computing checksum..."
 
-#FIXME: Continues even when hashdeep is missing
+mkfifo "$crystalWorkdir/$CrystalID".coal5
+mkfifo "$crystalWorkdir/$CrystalID".coal5-md5deep
 
-hashdeep -c md5,sha1,sha256 -o fbcpsde "$crystalWorkdir/$CrystalID".coal5 | tee "$crystalWorkdir/$CrystalID.checksums"
+#FIXME: Continues even when hashdeep is missing
+tee -a "$crystalWorkdir/$CrystalID".coal5 "$crystalWorkdir/$CrystalID".coal5-md5deep < "$crystalWorkdir/$CrystalID".pax.xz.gpg &
+sleep 1
+
+hashdeep -c md5,sha1,sha256 -o fbcpsde "$crystalWorkdir/$CrystalID".coal5-md5deep | tee "$crystalWorkdir/$CrystalID.checksums" &
+sleep 1
 
 echo "Sending..."
 
 script ${optb+/dev/null} ${opt+-e} ${opt+-c} crystallize-internal-ia ${opt+/dev/null}
+sleep 1
+
+wait "$tarpid"
+exitcode="$?"
+
+echo "Waiting..."
+wait
+
+echo "Done waiting."
+rm -v "$crystalWorkdir/$CrystalID".pax
+rm -v "$crystalWorkdir/$CrystalID".pax.xz
+rm -v "$crystalWorkdir/$CrystalID".pax.xz.gpg
+
+#Ignore exit code 1 from tar on Linux, which indicates files changed while reading; see http://stackoverflow.com/questions/20318852/tar-file-changed-as-we-read-it
+if [ "$exitcode" != "0" ] && [[ $OSTYPE != *inux* ]]; then
+    exit $exitcode
+fi
+if [ "$exitcode" != "1" ] && [ "$exitcode" != "0" ]; then
+    exit $exitcode
+fi
 
 echo "Retrieving remote index..."
 
