Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -121,9 +121,19 @@ while read -r streamRegistryPath; do
             if ! [[ -e "crystal-backup-meta/cbb-index/items.packs-done/${pointerFile%.bundle.pointer}" ]]; then
                 # This pack doesn't have a .identifier file, so it needs to be extracted separately
                 packTempDir="$(tempDir)"
-                cp "$pointerFile" "$packTempDir"
+                packDir="$PWD"
                 pushd "$packTempDir"
-                unxz --stdout - < "$packfileBasename" | tar -xf -
+                unxz --stdout - < "$packDir/$pointerFile" | tar -xf -
+                # MAINTENANCE: Code copied from sreg_read_stream
+                crystalFilePattern=".*.crystal-data"
+                crystalFilePatternMatches=( $crystalFilePattern )
+                localStoreCrystalName="${crystalFilePatternMatches[0]}"
+                if ! [[ -e "$localStoreCrystalName" ]]; then
+                    error-notify "Crystal info could not be found in the pointer $hashFull, so giving up immediately (retrying probably wouldn't help this)."
+                    numRetries="0"
+                    break
+                fi
+                localStoreCrystalIdentifier="$(<"$localStoreCrystalName"/identifier)"
                 popd
             fi
         done
