Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -102,22 +102,18 @@ while read -r streamRegistryPath; do
         streamRegistryRepoName="${streamRegistryPath%%\/*}"
         streamRegistryPathInRepo="${streamRegistryPath#*\/}"
         (
-            cd repositories
             if ! [[ -d "$streamRegistryRepoName" ]]; then
-                (
-                    mkdir "$streamRegistryRepoName"
-                    cd "$streamRegistryRepoName" || die "Could not cd to newly created directory $(pwd)/$streamRegistryRepoName!"
-                    git init
-                    git config core.sparseCheckout true
-                    git remote add -f origin "$streamRegistryRepoName.git"
-                    echo "$streamRegistryPathInRepo*" > .git/info/sparse-checkout
-                    git checkout "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
-                )
+                mkdir "$streamRegistryRepoName"
+                cd "repositories/$streamRegistryRepoName" || die "Could not cd to newly created directory $(pwd)/repositories/$streamRegistryRepoName!"
+                git init
+                git config core.sparseCheckout true
+                git remote add -f origin "$streamRegistryRepoName.git"
+                echo "$streamRegistryPathInRepo*" > .git/info/sparse-checkout
+                git checkout "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
+            else
+                cd "repositories/$streamRegistryRepoName" || die "Could not cd to repository directory $(pwd)/$streamRegistryPath!"
             fi
-            (
-                cd "$streamRegistryPath" || die "Could not cd to repository directory $(pwd)/$streamRegistryPath!"
-                git pull origin
-            )
+            git pull origin
         )
         # Go through this sreg and add all the crystals it uses to the index
 
