Update Git repository using egup-single

diff --git a/scripts/crystallize b/scripts/crystallize
--- a/scripts/crystallize
+++ b/scripts/crystallize
@@ -347,8 +347,9 @@ testDecrystDir="$(bigTempDir)"
 (
     cd "$testDecrystDir" || die "cd failed"
     if [[ "true" == "$offline" ]]; then
+        decrystallize --passphrase "$(<"$crystalWorkdir/NonfinalizedCrystals/$CrystalID/$CrystalID".tmp)" --lock-override "$CrystalID" 2>&1 || die "Could not decrystallize the finished crystal!"
     else
-    decrystallize --passphrase "$(<"$crystalWorkdir/NonfinalizedCrystals/$CrystalID/$CrystalID".tmp)" --lock-override "$CrystalID" 2>&1 || die "Could not decrystallize the finished crystal!"
+        decrystallize --passphrase "$(<"$crystalWorkdir/NonfinalizedCrystals/$CrystalID/$CrystalID".tmp)" --lock-override "$CrystalID" 2>&1 || die "Could not decrystallize the finished crystal!"
     fi
     rm "$crystalWorkdir/NonfinalizedCrystals/$CrystalID/$CrystalID.tmp"
 )
