Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -131,7 +131,12 @@ while read -r streamRegistryPath; do
                 shopt -s failglob
                 shopt -u nullglob
                 localStoreCrystalName="${crystalFilePatternMatches[0]}"
-                [[ -e "$localStoreCrystalName" ]] || die "Crystal info could not be found in the pointer for $pointerFile, so giving up immediately (retrying probably wouldn't help this)."
+                if ! [[ -e "$localStoreCrystalName" ]]; then
+                    warn "Crystal info could not be found in the pointer for $pointerFile, so giving up immediately and skipping this one (retrying probably wouldn't help this)."
+                    touch "$backupLocation/crystal-backup-meta/cbb-index/items.packs-done/${pointerFile%.bundle.pointer}"
+                    continue
+                fi
+                [[ -e "$localStoreCrystalName/identifier" ]] || die "Crystal info was found, but no crystal identifier was found in the pointer for $pointerFile."
                 echo "$(<"$localStoreCrystalName"/identifier)" >> "$backupLocation/crystal-backup-meta/cbb-index/items"
                 touch "$backupLocation/crystal-backup-meta/cbb-index/items.packs-done/${pointerFile%.bundle.pointer}"
                 spopd || die "Could not popd!"
