Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -121,7 +121,7 @@ while read -r streamRegistryPath; do
                 # This pack doesn't have a .identifier file, so it needs to be extracted separately
                 packTempDir="$(tempDir)"
                 packDir="$PWD"
-                pushd "$packTempDir"
+                pushd "$packTempDir" || die "Could not pushd to $packTempDir!"
                 unxz --stdout - < "$packDir/$pointerFile" | tar -xf -
                 # MAINTENANCE: Code copied and tweaked from sreg_read_stream
                 crystalFilePattern=".*.crystal-data"
@@ -131,6 +131,7 @@ while read -r streamRegistryPath; do
                 echo "$(<"$localStoreCrystalName"/identifier)" >> "crystal-backup-meta/cbb-index/items"
                 touch "crystal-backup-meta/cbb-index/items.packs-done/${pointerFile%.bundle.pointer}"
                 popd
+                rm -r "$packTempDir"
             fi
         done
 
