Update Ember tree

diff --git a/scripts/crystallize-bash_setup b/scripts/crystallize-bash_setup
--- a/scripts/crystallize-bash_setup
+++ b/scripts/crystallize-bash_setup
@@ -48,4 +48,26 @@ function sregi_available_by_hash() {
     fi
 }
 
+function sregi_hash_from_file() (
+    # Function is defined with parentheses to make it run in a subshell to prevent the definition of pipecheck clobbering other functions named that in the calling script
+    file="$1"
+    function pipecheck() {
+        (
+        pipeCheckTemp=("${PIPESTATUS[@]}")
+        if [[ "${pipeCheckTemp[0]}" != "141" ]] && [[ "${pipeCheckTemp[0]}" != "0" ]]; then
+            # Ignore status 141, which just means the input stream was terminated by head before all the data were consumed
+            die "Failed reading temporary stream file"
+        fi
+        if [[ "${pipeCheckTemp[1]}" != "0" ]]; then
+            die "Failed executing head on temporary stream file"
+        fi
+        )
+    }
+    set +o pipefail
+    tail -c +38 "$streamId.xz" | head -c 129
+    pipecheck
+    set -o pipefail
+    unset -f pipecheck
+)
+
 EmberLibrary="$(crystallize-getconf EmberLibrary)"
