Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -182,6 +182,19 @@ while read -r streamRegistryPath; do
                         packDir="$PWD"
                         spushd "$pointerTempDir" || die "Could not pushd to $pointerTempDir!"
                         tail -c +167 "$streamRegistryFullPath/$potentialPointer" | unxz --stdout - | tar -xf -
+                crystalFilePattern=".*.crystal-data"
+                shopt -u failglob
+                shopt -s nullglob
+                crystalFilePatternMatches=( $crystalFilePattern )
+                shopt -s failglob
+                shopt -u nullglob
+                localStoreCrystalName="${crystalFilePatternMatches[0]}"
+                if ! [[ -e "$localStoreCrystalName" ]]; then
+                    error-notify "Crystal info could not be found in the pointer $hashFull, so giving up immediately (retrying probably wouldn't help this)."
+                    numRetries="0"
+                    break
+                fi
+                localStoreCrystalIdentifier="$(<"$localStoreCrystalName"/identifier)"
                         crystallize-get-identifier-from-pointer ./*.crystal >> "$backupLocation/crystal-backup-meta/cbb-index/items"
                         spopd || die "Could not popd!"
                         rm -r "$pointerTempDir"
