version

diff --git a/scripts/crystallize-logsession b/scripts/crystallize-logsession
--- a/scripts/crystallize-logsession
+++ b/scripts/crystallize-logsession
@@ -3,7 +3,7 @@
 source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 set -x
 
 echo "The crystal will have the following address when it is ready: $CrystalID"
@@ -20,7 +20,7 @@ echo "Time (log stage 1) from http://timeapi.org/: "
 
 trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-start" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z";
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 echo "Time (log stage 1b) locally:"
 
@@ -62,7 +62,7 @@ echo "IP address from http://icanhazip.com/: "
 
 trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.ip" -e robots=off http://icanhazip.com/ &
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 echo "Time (log stage 2) locally:"
 
@@ -73,7 +73,7 @@ echo "Time (log stage 2) from http://timeapi.org/: "
 
 trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-env" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z" &
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 echo "Time (log stage 2b) locally:"
 
@@ -89,8 +89,7 @@ shift
 
 #Resolve relative paths in the arguments, since GNU tar's -P doesn't
 CrystallizePaths=( "$@" )
-# shellcheck disable=SC2128
-echo "First entry in array: $CrystallizePaths"
+echo "First entry in array: ${CrystallizePaths[0]}"
 for i in "${!CrystallizePaths[@]}"; do
     #resolve path
     echo "Trying to resolve ${CrystallizePaths[$i]}..."
@@ -173,7 +172,7 @@ trap - ERR
 #If GNU/Linux, set opt to 1 and unset optb; otherwise opposite
 [[ $OSTYPE = *inux* ]] && (( opt++ ))
 [[ $OSTYPE != *inux* ]] && (( optb++ ))
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 script ${optb+/dev/null} ${opt+-e} ${opt+-c} crystallize-internal-ia ${opt+/dev/null}
 
@@ -246,7 +245,7 @@ echo "Time (log stage 3) from http://timeapi.org/: "
 
 trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-done" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 echo "Time (log stage 3b) locally:"
 
diff --git a/scripts/localstorecache_request b/scripts/localstorecache_request
--- a/scripts/localstorecache_request
+++ b/scripts/localstorecache_request
@@ -6,7 +6,7 @@ source ember_bash_setup &> /dev/null
 # Usage: localstorecache_request <cache directory> <crystal identifier>
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
 dbDir="$1"
@@ -25,7 +25,7 @@ mkdir -p "$hashDir"
 dbLinkPath="$hashDir/$hashFull"
 
 # Clean up if there's an error to avoid leaving a broken cache entry
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
 
 # Remove the least-used items from the cache until it fits within the alloted disk space
 diskUsageLimit="$(<"$dbDir"/.localstorecache.limit)"
@@ -52,7 +52,7 @@ if [[ "$(du -sb "$dbDir" | awk '{print $1;}')" -gt "$diskUsageLimit" ]]; then
 fi
 trap - ERR
 oldFilePath="$(readlink "$dbLinkPath")"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 if [[ ! -h "$dbLinkPath" ]] || [[ ! -s "$oldFilePath" ]] || [[ ! -d "$oldFilePath"/scache-*.LocalStore ]]; then
     # Item is not in the cache, so add it
 
diff --git a/scripts/sreg_fsck b/scripts/sreg_fsck
--- a/scripts/sreg_fsck
+++ b/scripts/sreg_fsck
@@ -10,7 +10,7 @@ function finish() {
     rm -r "$crystalWorkdir/$fsckId"
   fi
 }
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 echo "Counting items..."
 crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
diff --git a/scripts/sreg_read_stream b/scripts/sreg_read_stream
--- a/scripts/sreg_read_stream
+++ b/scripts/sreg_read_stream
@@ -11,7 +11,7 @@ function finish() {
         rm -r "$streamId"
     fi
 }
-trap 'error-notify "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."; finish; exit 1' ERR
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; finish; exit 1' ERR
 
 if [[ "$1" == "--checksum" ]]; then
     shift
@@ -35,13 +35,13 @@ fi
 # Get stream
 mkdir "$streamId"
 (
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
     cd "$streamId" || exit 1
     sponge "$streamId.xz"
     numRetries=40
     numTotalRetries=40
     successfulRetrieval="0"
-    trap 'warn "A nonfatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+    trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
     # Get the hash of the stream
     hashFull="$(tail -c +38 "$streamId.xz" | head -c 129)"
     if [[ -n "$knownChecksum" ]]; then
@@ -153,7 +153,7 @@ mkdir "$streamId"
             successfulRetrieval="1"
         fi
     done
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
     if [[ "$successfulRetrieval" != "1" ]]; then
         error-die "Failed retrieving stream, and no retries left!"
     fi
diff --git a/scripts/sregi_copy_write b/scripts/sregi_copy_write
--- a/scripts/sregi_copy_write
+++ b/scripts/sregi_copy_write
@@ -5,7 +5,7 @@ source ember_bash_setup &> /dev/null
 # Copy $1 into $2 and replace with pointers. $1 cannot be a directory.
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 #set -x
 
 if [[ "$1" == "--no-verify" ]]; then
@@ -46,7 +46,7 @@ if [[ -f "$destinationName" ]]; then
     destinationChecksum=""
     hasEncounteredError="0"
     if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
-        trap 'warn "A nonfatal error was reported on ${BASH_SOURCE} line ${LINENO}."; hasEncounteredError="1"' ERR
+        trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; hasEncounteredError="1"' ERR
         assumePointerDbEntryFileExists="true"
         if [[ "$sregNoVerify" == "true" ]]; then
             destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
@@ -56,7 +56,7 @@ if [[ -f "$destinationName" ]]; then
             fi
         else
             destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
-            sreg_read_stream < "$destinationName" > /dev/null || 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."'
+            sreg_read_stream < "$destinationName" > /dev/null || error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."
         fi
         if [[ "$destinationChecksum" == "$sourceChecksum" && "$hasEncounteredError" == "0" && "$assumePointerDbEntryFileExists" == "true" ]]; then
             # The file is already present, pointerized, and readable, so exit without doing anything.
@@ -69,14 +69,14 @@ if [[ -f "$destinationName" ]]; then
         fi
     fi
 fi
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
 streamId="sreg-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
 crystalSubdir="$crystalWorkdir/$streamId"
 mkdir -p "$crystalSubdir"
 rsync -a --checksum --no-i-r "$1" "$crystalSubdir/"
 setVariableToCommandOutput "basename" "embasename" "$1"
-fileToStash="$crystalSubdir/$basename"
+fileToStash="$crystalSubdir/${basename:?}"
 echo "Begun storing $fileToStash."
 if [[ -f "$fileToStash" ]]; then
     sreg_store_stream --assume-checksum "$sourceChecksum" --verbose < "$fileToStash"
diff --git a/scripts/sregi_verify_hashpointer b/scripts/sregi_verify_hashpointer
--- a/scripts/sregi_verify_hashpointer
+++ b/scripts/sregi_verify_hashpointer
@@ -3,7 +3,7 @@
 source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 pointerTypeSignature="$(head -c 36 "$1")"
 knownChecksum=""
@@ -12,7 +12,7 @@ if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
     if ! sreg_read_stream --checksum "$knownChecksum" < "$1"; then
         trap - ERR
         mv "$2" "$2.CORRUPTED-HASHPOINTER"
-        trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
+        trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
         error-die "Item $1 did not match the stored checksum!"
     fi
 fi
