Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -101,16 +101,16 @@ fi
 # Get idents from Web site
 (
     if ! [[ -d "repositories/ember-web-site" ]]; then
-    cd repositories || die "Could not cd to repositories directory!"
-    git clone --no-checkout "ember-web-site.git"
-    cd "ember-web-site" || die "Could not cd to repository directory $(pwd)/ember-web-site!"
-    git init
-    git config core.sparseCheckout true
-    echo "identifiers.lst" > .git/info/sparse-checkout
-    git checkout
-                else
-                    cd "repositories/$streamRegistryRepoName" || die "Could not cd to repository directory $(pwd)/repositories/$streamRegistryRepoName!"
-                fi
+        cd repositories || die "Could not cd to repositories directory!"
+        git clone --no-checkout "ember-web-site.git"
+        cd "ember-web-site" || die "Could not cd to repository directory $(pwd)/ember-web-site!"
+        git init
+        git config core.sparseCheckout true
+        echo "identifiers.lst" > .git/info/sparse-checkout
+        git checkout
+    else
+        cd "repositories/ember-web-site" || die "Could not cd to repository directory $(pwd)/repositories/ember-web-site!"
+    fi
     git pull origin
 )
 print $'\n' >> "crystal-backup-meta/cbb-index/items"
