Update Git repository using egup-single

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -340,7 +340,7 @@ while read -r crystal; do
                 fi
             fi
         fi
-        crystallize-backup "$crystal"
+        crystallize-backup "$crystal" || die "Error backing up or checking the item known as $crystal!"
         numberProcessed="$(find "../crystal-backup-meta/completed-items/" -maxdepth 1 -printf a | wc -c | xargs)"
         numberProcessedPercentage="$(printf "%.3f\\n" "$(bc -l <<< "($numberProcessed"" / $numberExpected) * 100")")" # extra quotation marks to prevent turning "sed" into "gsed" on Mac ;)
         echo "Backed up $numberProcessed"" ($numberProcessedPercentage%) of $numberExpected total crystals." # extra quotation marks to prevent turning "sed" into "gsed" on Mac ;)
