Update Ember tree

diff --git a/scripts/crystallize b/scripts/crystallize
--- a/scripts/crystallize
+++ b/scripts/crystallize
@@ -2,12 +2,12 @@
 # shellcheck disable=SC1091
 source ember_bash_setup &> /dev/null
 
-export crystallizeVersion='3.1.1.1_pre6.1.1'
+export crystallizeVersion='3.1.1.1_pre6.2'
 
 # ( sudo echo; cd "/Ember Library/Ember satellite projects/crystallize"; git add -A .; git commit -m "version"; git tag -a v3.1.0.29 -m "version"; egup-single .; sudo emerge crystallize )
 
 ((EUID)) && exec sudo -- "$0" "$@"
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 if [[ ! -e "${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Crystal\ Index/ ]]; then
     echo "ERROR: Could not find a usable Ember Library directory tree. Nothing done."
@@ -77,7 +77,7 @@ if [[ $crystallizeLeavePointer == true ]]; then
     rsync -av --progress --checksum "$crystalWorkdir/$CrystalID.local.idx" "$crystalWorkdir/$CrystalID.deep.idx" "$crystalWorkdir/$CrystalID.cmd" "$crystalWorkdir/$CrystalID.cwd" "$crystallizePointerDir"/
     echo "Added crystal metadata"
 fi
-set +e
+trap - ERR
 xz -C sha256 -v -9 -e "$crystalWorkdir/$CrystalID"
 xz -C sha256 -v -9 -e -k "$crystalWorkdir/$CrystalID.time-done.warc.gz"
 xz -C sha256 -v -9 -e "$crystalWorkdir/$CrystalID.local.idx"
@@ -97,7 +97,7 @@ mv -v "$crystalWorkdir/$CrystalID.deep.idx.xz.gpg" "$crystalWorkdir/$CrystalID.c
 mv -v "$crystalWorkdir/$CrystalID.cmd.gpg" "$crystalWorkdir/$CrystalID.coal5-cmd"
 mv -v "$crystalWorkdir/$CrystalID.cwd.gpg" "$crystalWorkdir/$CrystalID.coal5-cwd"
 
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 ia upload "$CrystalID" --retries=100 --verify --delete "$crystalWorkdir/$CrystalID.coal5-log" "$crystalWorkdir/$CrystalID.coal5-idx-l" "$crystalWorkdir/$CrystalID.coal5-idx-d" "$crystalWorkdir/$CrystalID.coal5-cmd" "$crystalWorkdir/$CrystalID.coal5-cwd"
 ia upload "$CrystalID" --retries=100 --verify "$crystalWorkdir/$CrystalID.coal5-timestamp"
 
diff --git a/scripts/crystallize-logsession b/scripts/crystallize-logsession
--- a/scripts/crystallize-logsession
+++ b/scripts/crystallize-logsession
@@ -3,7 +3,7 @@
 source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 set -x
 
 echo "The crystal will have the following address when it is ready: $CrystalID"
@@ -18,9 +18,9 @@ export crystalWorkdir
 
 echo "Time (log stage 1) from http://timeapi.org/: "
 
-set +e
+trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-start" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z";
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 echo "Time (log stage 1b) locally:"
 
@@ -60,9 +60,9 @@ dig +short myip.opendns.com @resolver1.opendns.com
 
 echo "IP address from http://icanhazip.com/: "
 
-set +e
+trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.ip" -e robots=off http://icanhazip.com/ &
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 echo "Time (log stage 2) locally:"
 
@@ -71,9 +71,9 @@ xxd -pu <<< "$(date +%z)"
 
 echo "Time (log stage 2) from http://timeapi.org/: "
 
-set +e
+trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-env" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z" &
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 echo "Time (log stage 2b) locally:"
 
@@ -169,11 +169,11 @@ set -o pipefail
 unset opt
 unset optb
 
-set +e
+trap - ERR
 #If GNU/Linux, set opt to 1 and unset optb; otherwise opposite
 [[ $OSTYPE = *inux* ]] && (( opt++ ))
 [[ $OSTYPE != *inux* ]] && (( optb++ ))
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 script ${optb+/dev/null} ${opt+-e} ${opt+-c} crystallize-internal-ia ${opt+/dev/null}
 
@@ -244,9 +244,9 @@ xxd -pu <<< "$(date +%z)"
 
 echo "Time (log stage 3) from http://timeapi.org/: "
 
-set +e
+trap - ERR
 wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-done" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z"
-set -e
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 echo "Time (log stage 3b) locally:"
 
