version

diff --git a/scripts/crystallize-logsession b/scripts/crystallize-logsession
--- a/scripts/crystallize-logsession
+++ b/scripts/crystallize-logsession
@@ -3,7 +3,7 @@
 source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 #set -x
 
 logfile="$1"
@@ -24,7 +24,7 @@ echo "The crystal will have the following address when it is ready: $CrystalID" 
 
     trap - ERR
     wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-start" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z"
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
     echo "Time (log stage 1b) locally:"
 
@@ -66,7 +66,7 @@ echo "The crystal will have the following address when it is ready: $CrystalID" 
 
     trap - ERR
     wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.ip" -e robots=off http://icanhazip.com/ &
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
     echo "Time (log stage 2) locally:"
 
@@ -77,7 +77,7 @@ echo "The crystal will have the following address when it is ready: $CrystalID" 
 
     trap - ERR
     wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-env" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z" &
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
     echo "Time (log stage 2b) locally:"
 
@@ -179,7 +179,7 @@ trap - ERR
 #If GNU/Linux, set opt to 1 and unset optb; otherwise opposite
 [[ $OSTYPE = *inux* ]] && (( opt++ ))
 [[ $OSTYPE != *inux* ]] && (( optb++ ))
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 script ${optb+/dev/null} ${opt+-e} ${opt+-c} crystallize-internal-ia ${opt+/dev/null}
 
@@ -253,7 +253,7 @@ fi
 
     trap - ERR
     wget --delete-after --warc-file="$crystalWorkdir/$CrystalID.time-done" -e robots=off "http://www.timeapi.org/utc/now?\Y-\m-\d-\H-\M-\S-\6N-\z"
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
     echo "Time (log stage 3b) locally:"
 
diff --git a/scripts/fcache_request b/scripts/fcache_request
--- a/scripts/fcache_request
+++ b/scripts/fcache_request
@@ -6,7 +6,7 @@ source ember_bash_setup &> /dev/null
 # Usage: fcache_request <cache directory> <URL>
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 dbDir="$1"
 requestUrl="$2"
@@ -49,7 +49,7 @@ itemChecksum="$(sha512sum < "$dbLinkPath" | awk '{print $1;}')"
 if [[ "$itemChecksum" != "$knownChecksum" ]]; then
   mkdir -p "$dbDir/Failed Checksum"
   mv "$dbFilePath" "$dbDir/Failed Checksum/$(basename "$dbFilePath")"
-  error-die "File does not match what its checksum should be!"
+  die "File does not match what its checksum should be!"
 fi
 # First, make sure the link is good and fix it up if it's not.
 if ! [[ -e "$dbFilePath" ]]; then
diff --git a/scripts/localstorecache_init b/scripts/localstorecache_init
--- a/scripts/localstorecache_init
+++ b/scripts/localstorecache_init
@@ -7,7 +7,7 @@ source ember_bash_setup &> /dev/null
 # If the cache directory already exists, the current size limit will override the one provided as an argument.
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 if [[ -e "$1"/.localstorecache.limit ]]; then
     exit 0
diff --git a/scripts/localstorecache_request b/scripts/localstorecache_request
--- a/scripts/localstorecache_request
+++ b/scripts/localstorecache_request
@@ -6,7 +6,7 @@ source ember_bash_setup &> /dev/null
 # Usage: localstorecache_request <cache directory> <crystal identifier>
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 #set -x
 
 crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
@@ -26,7 +26,7 @@ mkdir -p "$hashDir"
 dbLinkPath="$hashDir/$hashFull"
 
 # Clean up if there's an error to avoid leaving a broken cache entry
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
 
 # Remove the least-used items from the cache until it fits within the alloted disk space
 diskUsageLimit="$(<"$dbDir"/.localstorecache.limit)"
@@ -53,7 +53,7 @@ if [[ "$(du -sb "$dbDir" | awk '{print $1;}')" -gt "$diskUsageLimit" ]]; then
 fi
 trap - ERR
 oldFilePath="$(readlink "$dbLinkPath")"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
 cacheEntryFileList=("$oldFilePath"/scache-*.LocalStore)
 if [[ ! -h "$dbLinkPath" ]] || [[ ! -f "$oldFilePath" ]] || [[ ! -d "${cacheEntryFileList[0]}" ]]; then
     # Item is not in the cache, so add it
diff --git a/scripts/sreg_read_stream b/scripts/sreg_read_stream
--- a/scripts/sreg_read_stream
+++ b/scripts/sreg_read_stream
@@ -35,7 +35,7 @@ fi
 # Get stream
 mkdir "$streamId"
 (
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
     cd "$streamId" || exit 1
     sponge "$streamId.xz"
     numRetries=40
@@ -45,7 +45,7 @@ mkdir "$streamId"
     # Get the hash of the stream
     hashFull="$(tail -c +38 "$streamId.xz" | head -c 129)"
     if [[ -n "$knownChecksum" ]]; then
-        [[ "$knownChecksum" == "$hashFull" ]] || error-die "The checksum provided by the pointer does not match the provided checksum."
+        [[ "$knownChecksum" == "$hashFull" ]] || die "The checksum provided by the pointer does not match the provided checksum."
     fi
     hashA="${hashFull:0:1}"
     hashB="${hashFull:1:1}"
@@ -100,7 +100,7 @@ mkdir "$streamId"
                 crystalFilePatternMatches=( $crystalFilePattern )
                 localStoreCrystalName="${crystalFilePatternMatches[0]}"
                 if ! [[ -e "$localStoreCrystalName" ]]; then
-                    error-die "Crystal info could not be found in the pointer, so giving up immediately (retrying probably wouldn't help this)."
+                    die "Crystal info could not be found in the pointer, so giving up immediately (retrying probably wouldn't help this)."
                 fi
                 localStoreCrystalIdentifier="$(<"$localStoreCrystalName"/identifier)"
                 localstoreLocation="$(localstorecache_request "$crystalWorkdir/.LocalStoreCache/" "$localStoreCrystalIdentifier")"
@@ -108,14 +108,14 @@ mkdir "$streamId"
             elif [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
                 # Hash pointer
                 if [[ "true" == "$disallowHashPointer" ]]; then
-                    error-die "The provided pointer is a hash pointer!"
+                    die "The provided pointer is a hash pointer!"
                 fi
                 if ! [[ -e "$dbDir/$hashA/$hashB/$hashC/$hashFull" ]]; then
-                    error-die "The provided pointer is a hash pointer, but the corresponding hash is not registered in the database! ($dbDir/$hashA/$hashB/$hashC/$hashFull does not exist.)"
+                    die "The provided pointer is a hash pointer, but the corresponding hash is not registered in the database! ($dbDir/$hashA/$hashB/$hashC/$hashFull does not exist.)"
                 fi
                 sreg_read_stream < "$dbDir/$hashA/$hashB/$hashC/$hashFull" > "$streamId.out"
             else
-                error-die "Unknown pointer type signature! Either the file is corrupted, or this is a pointer version this version of sreg_read_stream is not familiar with, or this is not a pointer. Aborting."
+                die "Unknown pointer type signature! Either the file is corrupted, or this is a pointer version this version of sreg_read_stream is not familiar with, or this is not a pointer. Aborting."
             fi
             mv "$streamId.out" "$dbFilePath"
             if [[ -h "$dbLinkPath" ]]; then
@@ -155,15 +155,15 @@ mkdir "$streamId"
             if [[ "$pointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]]; then
                 mkdir -p "$dbDir/LocalStore/Failed\ Fsck/"
                 mv "$dbDir/LocalStore/$hashA/$hashB/$hashC/$hashFull" "$dbDir/LocalStore/Failed\ Fsck/"
-                error-die "LocalStore entry was corrupted!"
+                die "LocalStore entry was corrupted!"
             fi
         else
             successfulRetrieval="1"
         fi
     done
-    trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
     if [[ "$successfulRetrieval" != "1" ]]; then
-        error-die "Failed retrieving stream, and no retries left!"
+        die "Failed retrieving stream, and no retries left!"
     fi
     cat "$dbLinkPath"
     # Cache cleanup is expensive, so only do it occasionally
diff --git a/scripts/sregi_bundle_pointer b/scripts/sregi_bundle_pointer
--- a/scripts/sregi_bundle_pointer
+++ b/scripts/sregi_bundle_pointer
@@ -2,7 +2,7 @@
 # shellcheck disable=SC1091
 source ember_bash_setup &> /dev/null
 
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 packPointerName="$1"
 dbDir="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Stream\ Registry
@@ -14,7 +14,7 @@ hashDir="$dbDir/$hashA/$hashB/$hashC"
 dbFilePath="$hashDir/$hashFull"
 if [[ -f "$dbFilePath" ]]; then
     if [[ "$(head -c 36 "$dbFilePath")" != "c39f8657-384b-438b-a5a2-eece17147589" ]]; then
-        error-die "The item $dbFilePath does not appear to be a LocalStore pointer! This is most likely a bug in sreg. Aborting to avoid messing things up."
+        die "The item $dbFilePath does not appear to be a LocalStore pointer! This is most likely a bug in sreg. Aborting to avoid messing things up."
     fi
 fi
 # 2fa... is the remote bundle pointer type signature
diff --git a/scripts/sregi_copy_write b/scripts/sregi_copy_write
--- a/scripts/sregi_copy_write
+++ b/scripts/sregi_copy_write
@@ -5,7 +5,7 @@ source ember_bash_setup &> /dev/null
 # Copy $1 into $2 and replace with pointers. $1 cannot be a directory.
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 #set -x
 
 if [[ "$1" == "--no-verify" ]]; then
@@ -56,7 +56,7 @@ if [[ -f "$destinationName" ]]; then
             fi
         else
             destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
-            sreg_read_stream < "$destinationName" > /dev/null || error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."
+            sreg_read_stream < "$destinationName" > /dev/null || die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."
         fi
         if [[ "$destinationChecksum" == "$sourceChecksum" && "$hasEncounteredError" == "0" && "$assumePointerDbEntryFileExists" == "true" ]]; then
             # The file is already present, pointerized, and readable, so exit without doing anything.
@@ -69,7 +69,7 @@ if [[ -f "$destinationName" ]]; then
         fi
     fi
 fi
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
 streamId="sreg-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
 crystalSubdir="$crystalWorkdir/$streamId"
@@ -82,7 +82,7 @@ if [[ -f "$fileToStash" ]]; then
     sreg_store_stream --assume-checksum "$sourceChecksum" --verbose < "$fileToStash"
     printf '%s\n%s\n' "760fa662-89cf-4ebd-9664-150b7637ddd4" "$sourceChecksum" > "$fileToStash"
 else
-    error-die "Skipping item $fileToStash: not a regular file."
+    die "Skipping item $fileToStash: not a regular file."
 fi
 echo "Done storing $fileToStash."
 mkdir -p "$(dirname "$destinationName")"
diff --git a/scripts/srsync b/scripts/srsync
--- a/scripts/srsync
+++ b/scripts/srsync
@@ -5,7 +5,7 @@ source ember_bash_setup &> /dev/null
 # Copy $1 into $2 and replace with pointers, skipping existing
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 #set -x
 
 sregNoVerify=true
@@ -20,7 +20,7 @@ if [[ "$sregNoVerify" == "true" ]]; then
     echo "(Not verifying pointers: use sreg_fsck to test the entire stream registry.)"
 fi
 if ! [[ -d "$2" ]]; then
-    error-die "Destination is not a directory."
+    die "Destination is not a directory."
 fi
 echo "Counting items..."
 crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
