Update Ember tree

diff --git a/scripts/crystallize b/scripts/crystallize
--- a/scripts/crystallize
+++ b/scripts/crystallize
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Crystallize
 # Version:
-export crystallizeVersion='2.14.2.8'
+export crystallizeVersion='2.14.2.9'
 
 [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
 
@@ -40,7 +40,7 @@ export CrystalID
 crystallize-logsession "$CrystalID" "$@" 2>&1 | tee -a "$crystalWorkdir/$CrystalID"
 
 echo "Working..."
-#Script should not exit if an operation fails.
+#Script should not exit if an operation fails. FIXME: why?
 set +e
 xz -C sha256 -v -9 -e "$crystalWorkdir/$CrystalID"
 xz -C sha256 -v -9 -e -k "$crystalWorkdir/$CrystalID.time-done.warc.gz"
@@ -56,6 +56,8 @@ mv -v "$crystalWorkdir/$CrystalID.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-log"
 mv -v "$crystalWorkdir/$CrystalID.time-done.warc.gz.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-timestamp"
 mv -v "$crystalWorkdir/$CrystalID.local.idx.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-idx-l"
 mv -v "$crystalWorkdir/$CrystalID.deep.idx.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-idx-d"
+
+set -e
 ia upload "$CrystalID" --retries=100 --verify --delete "$crystalWorkdir/$CrystalID.coal5-log" "$crystalWorkdir/$CrystalID.coal5-idx-l" "$crystalWorkdir/$CrystalID.coal5-idx-d"
 ia upload "$CrystalID" --retries=100 --verify "$crystalWorkdir/$CrystalID.coal5-timestamp"
 
