Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -148,9 +148,9 @@ while read -r streamRegistryPath; do
 
         spopd || die "Could not popd!"
 
-        spushd "$streamRegistryFullPath" || die "Could not pushd to Packs directory!"
+        spushd "$streamRegistryFullPath" || die "Could not pushd to stream registry directory!"
         shopt -s globstar
-        GLOBIGNORE="./.keep:./.sreg.root:./passphrase:./LocalStore*:./Packs*"
+        GLOBIGNORE=".keep:.sreg.root:passphrase:LocalStore*:Packs*"
         for potentialPointer in "$streamRegistryFullPath"/**; do
             if [[ -f "$potentialPointer" ]]; then
                 typeSignature="$(head -c 36 "$potentialPointer" | tr -d '\0')"
@@ -182,6 +182,7 @@ while read -r streamRegistryPath; do
         done
         unset GLOBIGNORE
         shopt -u globstar
+        spopd || die "Could not popd!"
     fi
 done <<< "$cbbStreamRegistries"
 pwd
