Update Ember tree

diff --git a/scripts/crystallize-logsession b/scripts/crystallize-logsession
--- a/scripts/crystallize-logsession
+++ b/scripts/crystallize-logsession
@@ -121,7 +121,7 @@ hashdeep -c md5,sha1,sha256,tiger,whirlpool -e -o fbsd -r "$crystalWorkdir/""$Cr
 echo "Counting size..."
 
 crystalFilesSize="$(du -c "$crystalWorkdir/""$CrystallizeFirstArg" "${CrystallizePaths[@]}" "$crystalWorkdir/$CrystalID" | tail -1 | cut -f 1)"
-crystalFilesSize=$((crystalFilesSize * 1000))
+crystalFilesSizeMult=$((crystalFilesSize * 1000))
 
 #get available memory
 memlimit=-1
@@ -134,7 +134,7 @@ if hash free 2>/dev/null; then
         memlimit="$(free | grep Mem: | awk 'FNR == 1 {print ($4+$6+$7)}')"
     fi
     #Output is in kilobytes
-    memlimit="$(($memlimit * 1000))"
+    memlimit="$((memlimit * 1000))"
 elif hash vm_stat 2>/dev/null; then
     #The system doesn't have the free command; try vm_stat
     #use sum of free+inactive from vm_stat
@@ -142,15 +142,15 @@ elif hash vm_stat 2>/dev/null; then
     free="${freel::${#freel}-1}"
     inactivel="$(vm_stat | grep "Pages inactive:" | awk 'FNR == 1 {print ($3)}')"
     inactive="${inactivel::${#inactivel}-1}"
-    memlimit="$(($free + $inactive))"
+    memlimit="$((free + inactive))"
     #Output is in 4096-byte pages
-    memlimit="$(($memlimit * 4096))"
+    memlimit="$((memlimit * 4096))"
 else
     echo "Warning: Could not determine how much memory is available."
     sleep 3
 fi
 
-memlimit="$(($memlimit - 1073741824))"
+memlimit="$((memlimit - 1073741824))"
 
 echo "cd \"$(pwd)\""
 echo "CrystalID=\"$CrystalID\""
@@ -159,13 +159,36 @@ echo "crystalTitle=\"$crystalTitle\""
 echo "crystallizeVersion=\"$crystallizeVersion\""
 echo "crystalCollection=\"$crystalCollection\""
 
+crystallizeAccessKey="$(grep access ~/.config/ia.ini | head -n 1 | awk '{ print $3 }')"
+crystallizeSecretKey="$(grep secret ~/.config/ia.ini | head -n 1 | awk '{ print $3 }')"
+
+CrystalFileName="$(basename "$crystalWorkdir/$CrystalID".coal5)"
+
 echo "Sending..."
 #FIXME: May continue even when hashdeep is missing
 #pack files into stream | measure rate of stream's flow | compress the stream | encrypt the stream | send the input to a checksummer and to the output | send the stream to ia
-#FIXME: Replace ia with curl (use Content-MD5 HTTP header in request for verification https://github.com/jjjake/internetarchive/blob/28dfa989abd8e21d1827dd4194014c1ea3770b1a/internetarchive/item.py#L558)
-tar -cv -P -S --format pax "$crystalWorkdir/""$CrystallizeFirstArg" "${CrystallizePaths[@]}" "$crystalWorkdir/$CrystalID" "$crystalWorkdir/$CrystalID.local.idx" "$crystalWorkdir/$CrystalID.deep.idx" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.time-start.warc.gz" "$crystalWorkdir/$CrystalID.ip.warc.gz" "$crystalWorkdir/$CrystalID.time-env.warc.gz" | xz -k -C sha256 -T 0 --lzma2=preset=1 --memlimit-compress="$memlimit" --stdout - | gpg --yes -c -v --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp - | tee >(hashdeep -c md5,sha1,sha256 -o fbcpsde > "$crystalWorkdir/$CrystalID.checksums") | pv -tparbIfei 0.1 -s "$crystalFilesSize" | ia upload "$CrystalID" - --remote-name="$(basename "$crystalWorkdir/$CrystalID".coal5)" --verify --retries=100 --metadata="subject:Uploaded using Crystallize $crystallizeVersion" --metadata="subject:1EA21BD8-DB7E-11E5-9733-728C37852114" --metadata=subject:"$crystalTitle" --metadata=subject:"$CrystalID" --metadata="collection:$crystalCollection" --debug
+sendRetries=0
+until [ $sendRetries -ge 100 ]; do
+    tar -cv -P -S --format pax "$crystalWorkdir/""$CrystallizeFirstArg" "${CrystallizePaths[@]}" "$crystalWorkdir/$CrystalID" "$crystalWorkdir/$CrystalID.local.idx" "$crystalWorkdir/$CrystalID.deep.idx" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.tmp" "$crystalWorkdir/$CrystalID.time-start.warc.gz" "$crystalWorkdir/$CrystalID.ip.warc.gz" "$crystalWorkdir/$CrystalID.time-env.warc.gz" | xz -k -C sha256 -T 0 --lzma2=preset=1 --memlimit-compress="$memlimit" --stdout - | gpg --yes -c -v --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp - | tee >(hashdeep -c md5,sha1,sha256 -o fbcpsde > "$crystalWorkdir/$CrystalID.checksums") | pv -tparbIfei 0.1 -s "$crystalFilesSizeMult" | curl --location --header "x-amz-auto-make-bucket:1" --header "x-archive-queue-derive:0" --header "x-archive-size-hint:$crystalFilesSize" --header "authorization: LOW $crystallizeAccessKey:$crystallizeSecretKey" --header "x-archive-meta-collection:$crystalCollection" --header "x-archive-meta-title:$CrystalID" --header "x-archive-meta-description:%s" --header "x-archive-meta-subject:Uploaded using Crystallize $crystallizeVersion; 1EA21BD8-DB7E-11E5-9733-728C37852114; $crystalTitle; $CrystalID" --upload-file "-" "http://s3.us.archive.org/$CrystalID/$CrystalFileName" && break
+    sendRetries=$((sendRetries+1))
+    sleep 30
+done
 
-curl --location --header 'x-amz-auto-make-bucket:1' --header 'x-archive-queue-derive:0' --header 'x-archive-size-hint:%d' --header 'authorization: LOW %s:%s' --header 'x-archive-meta-mediatype:web' --header 'x-archive-meta-collection:%s' --header 'x-archive-meta-title:%s' --header 'x-archive-meta-description:%s' --header 'x-archive-meta-subject:a; b' --upload-file - http://s3.us.archive.org/ident/filename
+getChecksumRetries=0
+until [ $getChecksumRetries -ge 1000 ]; do
+    wget -qO - https://archive.org/download/"$CrystalID/$CrystalID"_files.xml | grep "<file name=\"$CrystalFileName\" source=\"original\">" && break
+    getChecksumRetries=$((getChecksumRetries+1))
+    sleep 30
+done
+
+checksumLine="$(wget -qO - https://archive.org/download/"$CrystalID/$CrystalID"_files.xml | grep -A 3 "<file name=\"$CrystalFileName\" source=\"original\">" | tail -n 1)"
+checksumLine="${checksumLine/    <md5>/}"
+checksumLine="${checksumLine/<\/md5>/}"
+knownChecksum="$(grep ",stdin" "$crystalWorkdir/$CrystalID.checksums" | awk -F',' '{print $2}')"
+if [[ $checksumLine != $knownChecksum ]]; then
+    echo "ERROR! Checksum known by Internet Archive does not match checksum known locally." >&2
+    exit 1
+fi
 
 exitcode="${PIPESTATUS[0]}"
 
