version

diff --git a/scripts/crystallize b/scripts/crystallize
--- a/scripts/crystallize
+++ b/scripts/crystallize
@@ -2,7 +2,7 @@
 # shellcheck disable=SC1091
 source ember_bash_setup &> /dev/null
 
-export crystallizeVersion='3.1.2_pre2.2.1'
+export crystallizeVersion='3.1.2_pre2.2.2'
 
 # ( sudo echo; cd "/Ember Library/Ember satellite projects/crystallize"; git add -A .; git commit -m "version"; git tag -a v3.1.0.29 -m "version"; egup-single .; sudo emerge crystallize )
 
@@ -113,7 +113,9 @@ done
 #Delete everything except log
 #echo "Cleaning up..."
 set +o pipefail
-yes | rm -r "${CrystallizePaths[@]}"
+trap - ERR
+yes | rm -rf "${CrystallizePaths[@]}"
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 set -o pipefail
 echo "Done cleaning up..."
 
