Update Git repository using egup-single

diff --git a/scripts/crystallize-bash_setup b/scripts/crystallize-bash_setup
--- a/scripts/crystallize-bash_setup
+++ b/scripts/crystallize-bash_setup
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 #set -x
 
-export emberCrystallizeVersion='3.1.2.5.14.169;'
+export emberCrystallizeVersion='3.1.2.5.14.170;'
 
 # The update script shown here requires there to be only one ebuild of crystallize in the wreathe-overlay overlay.
-# ( sudo true; newVersion="3.1.2.5.14.169"; cd "/Ember Library/Ember satellite projects/crystallize"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/crystallize/crystallize-*.ebuild "app-misc/crystallize/crystallize-$newVersion.ebuild"; repoman manifest; egup-single; sudo emerge --sync wreathe-overlay; sudo emerge crystallize; sudo dispatch-conf )
+# ( sudo true; newVersion="3.1.2.5.14.170"; cd "/Ember Library/Ember satellite projects/crystallize"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/crystallize/crystallize-*.ebuild "app-misc/crystallize/crystallize-$newVersion.ebuild"; repoman manifest; egup-single; sudo emerge --sync wreathe-overlay; sudo emerge crystallize; sudo dispatch-conf )
 
 rubberfs() {
     if [[ "$1" == "cd" ]]; then
         name="$2"
-        if [[ ! -n "$name" ]]; then
+        if [[ -z "$name" ]]; then
             name="library"
         fi
         cd "/Wreathe/.Resources/RubberFS/$name/mount" || exit 1
@@ -37,7 +37,23 @@ iu() {
     quickliquid "$@"
 }
 
-# Function is defined with parentheses to make it run in a subshell to prevent the "die" affecting the calling script (the calling script should be responsible for trapping/handling nonzero exit codes itself)
+crystallize_quick_unpack() {
+    local fileToUnpack
+    fileToUnpack="$1"
+    local unpackDate
+    unpackDate="$(emdate)"
+    local crystallizePassphrase
+    crystallizePassphrase="$(crystallize-getconf Passphrase)"
+    local passphraseTempfile
+    passphraseTempfile="$(tempFile)"
+    printf "%s" "$crystallizePassphrase" > "$passphraseTempfile"
+    gpg --yes --batch --passphrase-file "$passphraseTempfile" - < "$fileToUnpack" > "$fileToUnpack.unpacked-$unpackDate.unpacked" || { printf "%s" "example-crystal-passphrase" > "$passphraseTempfile"; gpg --yes --batch --passphrase-file "$passphraseTempfile" - < "$fileToUnpack" > "$fileToUnpack.unpacked-$unpackDate.unpacked"; }
+    unxz --stdout - < "$fileToUnpack.unpacked-$unpackDate.unpacked" > "$fileToUnpack.unpacked-$unpackDate.unpacked.unxz" || { echo "(Unxz failed; either the file wasn't compressed or is broken.)"; rm "$fileToUnpack.unpacked-$unpackDate.unpacked.unxz"; }
+    [[ -e "$fileToUnpack.unpacked-$unpackDate.unpacked.unxz" ]] && mv "$fileToUnpack.unpacked-$unpackDate.unpacked.unxz" "$fileToUnpack.unpacked-$unpackDate.unpacked"
+    echo "Done quick unpacking; result is at $fileToUnpack.unpacked-$unpackDate.unpacked."
+}
+
+#Function is defined with parentheses to make it run in a subshell to prevent the "die" affecting the calling script (the calling script should be responsible for trapping/handling nonzero exit codes itself)
 sregi_available_by_hash() (
     trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
