Update Ember tree

diff --git a/scripts/crystallize-fuse b/scripts/crystallize-fuse
--- a/scripts/crystallize-fuse
+++ b/scripts/crystallize-fuse
@@ -21,6 +21,10 @@ fi
 
 case $action in
 create)
+    if [ -e "/$name" ]; then
+        echo "ERROR: The requested name \"$name\" is already in use."
+        exit 1
+    fi
     mkdir -p "/Wreathe/.Resources/RubberFS/$name/dev/"
     #4T doesn't work: "truncate: failed to truncate '/Wreathe/.Resources/RubberFS/library/dev/StorageBlockDevice1' at 4398046511104 bytes: File too large" — wtf?! I don't have 3tb available either.
     truncate -s 3T "/Wreathe/.Resources/RubberFS/$name/dev/StorageBlockDevice1"
