Update Git repository using egup-single

diff --git a/scripts/crystallize-logsession b/scripts/crystallize-logsession
--- a/scripts/crystallize-logsession
+++ b/scripts/crystallize-logsession
@@ -312,11 +312,11 @@ if [[ "false" == "$completeOnly" ]]; then
     {
         echo "Please wait, pre-testing item before upload..."
         tempTestDecrystId="$(crystallize-getconf WorkDirectory)/.unpack-test-$(date-uuid)"
-        #trap 'rm -r "${tempTestDecrystId:?}"; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+        trap 'rm -r "${tempTestDecrystId:?}"; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
         (
             mkdir "$tempTestDecrystId"
-            #trap 'rm -r "${tempTestDecrystId:?}"; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
-            #trap 'rm -r "${tempTestDecrystId:?}"' EXIT
+            trap 'rm -r "${tempTestDecrystId:?}"; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+            trap 'rm -r "${tempTestDecrystId:?}"' EXIT
             crystalXzFileSize="$(disk-size-in-bytes "$CrystalTmpUploadFile")"
             pv -tparbIfei 0.1 -s "$crystalXzFileSize" < "$CrystalTmpUploadFile" | gpg --yes --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp - | unxz --stdout - | tar -xvf - -C "$tempTestDecrystId/" || die "Could not extract the local packed crystal!"
 
@@ -336,8 +336,7 @@ if [[ "false" == "$completeOnly" ]]; then
 
             cp "$crystalWorkdir/$CrystalID.csum" "$tempTestDecrystId.csum"
             cd "$tempTestDecrystId" || die "cd failed"
-            ls -lsa
-            find . -name "$CrystalID"'*' -not -name "$CrystalID.ostype" -not -name "$CrystalID.forks" -not -name "$CrystalID.forks-csum" -delete || die
+            find . -path "./$CrystalID"'*' -not -name "$CrystalID.ostype" -not -name "$CrystalID.forks" -not -name "$CrystalID.forks-csum" -print -delete || die
             csum --check ./* "$tempTestDecrystId.csum" || die
         ) || die
         rm -r "${tempTestDecrystId:?}"
