Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -103,15 +103,16 @@ while read -r streamRegistryPath; do
         streamRegistryPathInRepo="${streamRegistryPath#*\/}"
         (
             if ! [[ -d "repositories/$streamRegistryRepoName" ]]; then
-                mkdir "repositories/$streamRegistryRepoName"
-                cd "repositories/$streamRegistryRepoName" || die "Could not cd to newly created directory $(pwd)/repositories/$streamRegistryRepoName!"
+                cd repositories
+                git clone --no-checkout "$streamRegistryRepoName.git"
+                cd "$streamRegistryRepoName" || die "Could not cd to repository directory $(pwd)/repositories/$streamRegistryRepoName!"
                 git init
                 git config core.sparseCheckout true
                 git remote add -f origin "../$streamRegistryRepoName.git"
                 echo "$streamRegistryPathInRepo*" > .git/info/sparse-checkout
                 git checkout "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
             else
-                cd "repositories/$streamRegistryRepoName" || die "Could not cd to repository directory $(pwd)/repositories/$streamRegistryPath!"
+                cd "repositories/$streamRegistryRepoName" || die "Could not cd to repository directory $(pwd)/repositories/$streamRegistryRepoName!"
             fi
             git pull origin
         )
