Update Git repository using egup-single

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -319,6 +319,13 @@ while read -r crystal; do
 done <<< "$cbbCrystals"
 
 # [[ "$gitCommit" == "true" ]] && csum "$backupLocation" > ../crystal-backup-meta/.csum
+pushd ../crystal-backup-meta/ || die "Could not pushd"
+if [[ -f "./.csum" ]]; then
+    rm -f ./.csum.split*
+    split -l 100000 --numeric-suffixes .csum ".csum.split"
+    find . -maxdepth 1 -type f -name '.csum.split*' -exec mv {} {}.split \;
+fi
+popd
 
 [[ "$gitCommit" == "true" ]] && git add -A .
 { [[ "$gitCommit" == "true" ]] && git commit -m "Update" > /dev/null; } || true
