Update Ember tree

diff --git a/scripts/crystallize b/scripts/crystallize
--- a/scripts/crystallize
+++ b/scripts/crystallize
@@ -10,10 +10,10 @@ fi
 source ember_bash_setup &> /dev/null
 #set -x
 
-export crystallizeVersion='3.1.2.5.13.3'
+export crystallizeVersion='3.1.2.5.13.4'
 
 # The update script shown here requires there to be only one ebuild of crystallize in the wreathe-overlay overlay.
-# ( sudo true; newVersion="3.1.2.5.13.3"; cd "/Ember Library/Ember satellite projects/crystallize"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/crystallize/crystallize-*.ebuild "app-misc/crystallize/crystallize-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge crystallize; sudo dispatch-conf )
+# ( sudo true; newVersion="3.1.2.5.13.4"; cd "/Ember Library/Ember satellite projects/crystallize"; eogup-single; git tag -a "v$newVersion" -m "version"; egup-single .; cd "/Ember Library/Ember satellite projects/wreathe-overlay"; eogup-single; mv app-misc/crystallize/crystallize-*.ebuild "app-misc/crystallize/crystallize-$newVersion.ebuild"; repoman manifest; egup-single; sudo layman -s wreathe-overlay; sudo emerge crystallize; sudo dispatch-conf )
 
 ((EUID)) && exec sudo -- "$0" "$@"
 
@@ -288,7 +288,7 @@ echo "Please wait, testing finished item..."
 testDecrystDir="$(tempDir)"
 (
     cd "$testDecrystDir" || die "cd failed"
-    decrystallize --passphrase "$(<"$crystalWorkdir/$CrystalID".tmp)" "$CrystalID" || die "Could not decrystallize the finished crystal!"
+    decrystallize --passphrase "$(<"$crystalWorkdir/$CrystalID".tmp)" --checksum "$CrystalID" || die "Could not decrystallize the finished crystal!"
     rm "$crystalWorkdir/$CrystalID.tmp"
 )
 rm -r "${testDecrystDir:?}"
diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -17,6 +17,12 @@ if [[ "$1" == "--passphrase" ]]; then
     shift
 fi
 
+requireChecksum="false"
+if [[ "$2" == "--checksum" ]]; then
+    requireChecksum="true"
+    shift
+fi
+
 decrystallizeHere="false"
 if [[ "$2" == "--here" ]]; then
     decrystallizeHere="true"
@@ -67,7 +73,7 @@ if [[ "$exitStatus" == "0" ]]; then
     mkdir "$tempId.tempDir"
     (
         cd "$tempId"
-        find . -name "$CrystalID"'*' -exec bash -c 'dir="$(dirname "$0")"; mkdir -p "'"$tempId"'.tempDir/$dir/"; mv "$0" "../'"$tempId"'.tempDir/$dir/"' {} \; || die
+        find . -name "$CrystalID"'*' -exec bash -c 'dir="$(dirname "$0")"; mkdir -p "../'"$tempId"'.tempDir/$dir/"; mv "$0" "../'"$tempId"'.tempDir/$dir/"' {} \; || die
     ) || die
 
     (
@@ -81,6 +87,9 @@ if [[ "$exitStatus" == "0" ]]; then
     ) || die
     rm -r "${tempId:?}.tempDir"
 else
+    if [[ "$requireChecksum" == "true" ]]; then
+        die "Error retrieving csum file for this crystal, and checksumming was specified as being required!"
+    fi
     warn "(Couldn't retrieve csum file for this crystal; contents will not be checked for checksum errors.)"
 fi
 rm -f "${tempId:?}.csum"
