Update Git repository using egup-single

diff --git a/scripts/crystallize b/scripts/crystallize
--- a/scripts/crystallize
+++ b/scripts/crystallize
@@ -167,134 +167,135 @@ if [[ "false" == "$offline" ]]; then
     if [[ "false" == "$completeOnly" ]]; then
         trap 'cat "$crystalWorkdir/NonfinalizedCrystals/$CrystalID" || true; finishclean; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
     fi
-ia upload "$CrystalID" --retries=100 --verify --delete "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-log" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-idx-l" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-idx-d" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-csum" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-cmd" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-cwd" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-ostype" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-forks" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-forks-csum" 2>&1
-ia upload "$CrystalID" --retries=100 --verify "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-timestamp" 2>&1
+    ia upload "$CrystalID" --retries=100 --verify --delete "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-log" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-idx-l" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-idx-d" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-csum" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-cmd" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-cwd" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-ostype" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-forks" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-forks-csum" 2>&1
+    ia upload "$CrystalID" --retries=100 --verify "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5-timestamp" 2>&1
 
-echo "Please wait..."
+    echo "Please wait..."
 
-# Check that things were correctly uploaded
+    # Check that things were correctly uploaded
 
-sleep 2
+    sleep 2
 
-postUploadCheckSuccess=""
-postUploadCheckFailHandler() {
-    if [[ -z "$postUploadCheckSuccess" ]] || [[ "$postUploadCheckSuccess" == "1" ]]; then
-        postUploadCheckSuccess=1
-    else
-        postUploadCheckSuccess=0
+    postUploadCheckSuccess=""
+    postUploadCheckFailHandler() {
+        if [[ -z "$postUploadCheckSuccess" ]] || [[ "$postUploadCheckSuccess" == "1" ]]; then
+            postUploadCheckSuccess=1
+        else
+            postUploadCheckSuccess=0
+        fi
+    }
+
+    getChecksumRetries=0
+    retryDelayTime=5
+    until [[ "$getChecksumRetries" -ge 1000 ]]; do
+        if ia downloadAsStream --no-cache-metadata https://archive.org/download/"$CrystalID/$CrystalID"_files.xml | grep -F "<file name=\"$CrystalID.coal5\" source=\"original\">" > /dev/null; then
+            postUploadCheckFailHandler
+            break
+        fi
+        getChecksumRetries=$((getChecksumRetries+1))
+        sleep "$retryDelayTime"
+        if [[ "$retryDelayTime" -lt 30 ]]; then
+            retryDelayTime=$((retryDelayTime + 5))
+        fi
+    done
+
+    knownChecksum="$(grep ",stdin" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.checksums" | awk -F',' '{print $3}')"
+
+    retryUntilSuccess 1000 60 5 5 iasha1 "$CrystalID/$CrystalID.coal5" > /dev/null || die "Number of allowed retries exceeded without success."
+    checksumLine="$(retryUntilSuccess 1000 60 5 5 iasha1 "$CrystalID/$CrystalID.coal5")" || die "Number of allowed retries exceeded without success."
+
+    # First, check against the stored checksum
+    if [[ "$checksumLine" != "$knownChecksum" ]]; then
+        die "ERROR! Checksum known by Internet Archive $checksumLine does not match saved checksum known locally $knownChecksum."
     fi
-}
 
-getChecksumRetries=0
-retryDelayTime=5
-until [[ "$getChecksumRetries" -ge 1000 ]]; do
-    if ia downloadAsStream --no-cache-metadata https://archive.org/download/"$CrystalID/$CrystalID"_files.xml | grep -F "<file name=\"$CrystalID.coal5\" source=\"original\">" > /dev/null; then
-        postUploadCheckFailHandler
-        break
+    # Now, check the local file's checksum again in case it's gotten damaged in the mean time somehow
+    knownChecksum="$(hashdeep -c sha1 -j0 -o fbcpsde < "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5" | grep ",stdin" | awk -F',' '{print $2}')"
+    if [[ "$checksumLine" != "$knownChecksum" ]]; then
+        die "ERROR! Checksum known by Internet Archive $checksumLine does not match new checksum known locally $knownChecksum."
     fi
-    getChecksumRetries=$((getChecksumRetries+1))
-    sleep "$retryDelayTime"
-    if [[ "$retryDelayTime" -lt 30 ]]; then
-        retryDelayTime=$((retryDelayTime + 5))
+
+    getChecksumRetries=0
+    retryDelayTime=5
+    until [[ $getChecksumRetries -ge 1000 ]]; do
+        if ia downloadAsStream --no-cache-metadata https://archive.org/download/"$CrystalID/$CrystalID"_files.xml | grep -F "<file name=\"$CrystalID.coal5-timestamp\" source=\"original\">" > /dev/null; then
+            postUploadCheckFailHandler
+            break
+        fi
+        getChecksumRetries=$((getChecksumRetries+1))
+        sleep $retryDelayTime
+        if [[ $retryDelayTime -lt 30 ]]; then
+            retryDelayTime=$((retryDelayTime + 5))
+        fi
+    done
+
+    if [[ "$postUploadCheckSuccess" != "1" ]]; then
+        die "ERROR! Post-upload check failed: data appear to not have been transferred successfully!"
     fi
-done
 
-knownChecksum="$(grep ",stdin" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.checksums" | awk -F',' '{print $3}')"
+    echo "Retrieving remote index..."
 
-retryUntilSuccess 1000 60 5 5 iasha1 "$CrystalID/$CrystalID.coal5" > /dev/null || die "Number of allowed retries exceeded without success."
-checksumLine="$(retryUntilSuccess 1000 60 5 5 iasha1 "$CrystalID/$CrystalID.coal5")" || die "Number of allowed retries exceeded without success."
+    rm -f "$crystalWorkdir/NonfinalizedCrystals/$CrystalID".json.xz
+    { retryUntilSuccess 100 30 5 5 wget --delete-after --save-headers --output-document - "https://archive.org/metadata/$CrystalID/" > "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.json"; } 2>&1
+    checkedxz "$crystalWorkdir/NonfinalizedCrystals/$CrystalID".json -C sha256 -9 -e -v 2>&1
 
-# First, check against the stored checksum
-if [[ "$checksumLine" != "$knownChecksum" ]]; then
-    die "ERROR! Checksum known by Internet Archive $checksumLine does not match saved checksum known locally $knownChecksum."
-fi
+    rsync -av --progress --checksum "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.json.xz" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.checksums" "${EmberLibrary:?}"/CrystalIndex/
 
-# Now, check the local file's checksum again in case it's gotten damaged in the mean time somehow
-knownChecksum="$(hashdeep -c sha1 -j0 -o fbcpsde < "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5" | grep ",stdin" | awk -F',' '{print $2}')"
-if [[ "$checksumLine" != "$knownChecksum" ]]; then
-    die "ERROR! Checksum known by Internet Archive $checksumLine does not match new checksum known locally $knownChecksum."
-fi
+    rm "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.json.xz" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.checksums"
 
-getChecksumRetries=0
-retryDelayTime=5
-until [[ $getChecksumRetries -ge 1000 ]]; do
-    if ia downloadAsStream --no-cache-metadata https://archive.org/download/"$CrystalID/$CrystalID"_files.xml | grep -F "<file name=\"$CrystalID.coal5-timestamp\" source=\"original\">" > /dev/null; then
-        postUploadCheckFailHandler
-        break
+    # Next section registers the newly created crystal in the CrystalCache so an immediate decrystallize doesn't need to re-download it.
+
+    if ! [[ -e "$crystalWorkdir/.CrystalCache/" ]]; then
+        fcache_init "$crystalWorkdir/.CrystalCache/"
     fi
-    getChecksumRetries=$((getChecksumRetries+1))
-    sleep $retryDelayTime
-    if [[ $retryDelayTime -lt 30 ]]; then
-        retryDelayTime=$((retryDelayTime + 5))
+
+    dbDir="$crystalWorkdir/.CrystalCache/"
+    scache_gc "$dbDir" "f"
+
+    requestUrl="https://archive.org/download/$CrystalID/$CrystalID.coal5"
+    hashFull="$(sha512sum <<< "$requestUrl" | awk '{print $1;}')"
+    hashA="${hashFull:0:1}"
+    hashB="${hashFull:1:1}"
+    hashC="${hashFull:2:1}"
+    hashSubdir="$hashA/$hashB/$hashC"
+    hashDir="$dbDir/$hashSubdir"
+    mkdir -p "$hashDir"
+    dbLinkPath="$hashDir/$hashFull"
+    checksumName="$dbLinkPath.checksum"
+
+    finish() {
+        rm -f "${dbLinkPath:?}.locked"
+    }
+    trap finish EXIT
+    # Don't remove .coal5 file if it fails after this point
+    trap 'cat "$crystalWorkdir/NonfinalizedCrystals/$CrystalID" || true; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+
+    [[ -e "$dbLinkPath.locked" ]] && die "This URL cache entry (for a supposedly new crystal) is already in use. This should never happen, and indicates a bug in crystallize."
+
+    if [[ -e "$dbLinkPath" ]] || [[ -h "$dbLinkPath" ]]; then
+        die "This URL cache entry (for a supposedly new crystal) already exists. This should never happen, and indicates a bug in crystallize."
     fi
-done
 
-if [[ "$postUploadCheckSuccess" != "1" ]]; then
-    die "ERROR! Post-upload check failed: data appear to not have been transferred successfully!"
-fi
+    [[ -e "$checksumName" ]] && die "This URL cache entry (for a supposedly new crystal) already has a checksum file. This should never happen, and indicates a bug in crystallize."
 
-echo "Retrieving remote index..."
+    echo "locked on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)" > "$dbLinkPath.locked"
 
-rm -f "$crystalWorkdir/NonfinalizedCrystals/$CrystalID".json.xz
-{ retryUntilSuccess 100 30 5 5 wget --delete-after --save-headers --output-document - "https://archive.org/metadata/$CrystalID/" > "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.json"; } 2>&1
-checkedxz "$crystalWorkdir/NonfinalizedCrystals/$CrystalID".json -C sha256 -9 -e -v 2>&1
+    requestCount=0
+    dbFileDir="$dbDir/ByCount/${requestCount:?}/$hashSubdir"
+    dbFilePath="$dbFileDir/$hashFull"
+    mkdir -p "$dbFileDir"
+    mv "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5" "$dbFilePath"
+    sha512sum < "$dbFilePath" | awk '{print $1;}' > "$checksumName"
+    printf "%s" "$requestUrl" > "$dbLinkPath.url"
 
-rsync -av --progress --checksum "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.json.xz" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.checksums" "${EmberLibrary:?}"/CrystalIndex/
+    [[ -e "$dbLinkPath" ]] && [[ ! -h "$dbLinkPath" ]] && warn "Cache entry has something that's not a link at the place the link should be ($dbLinkPath). Huh? Removing it." && rm "$dbLinkPath"
+    [[ -h "$dbLinkPath" ]] && rm "$dbLinkPath"
+    ln -s "$dbFilePath" "$dbLinkPath"
 
-rm "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.json.xz" "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.checksums"
-
-# Next section registers the newly created crystal in the CrystalCache so an immediate decrystallize doesn't need to re-download it.
-
-if ! [[ -e "$crystalWorkdir/.CrystalCache/" ]]; then
-    fcache_init "$crystalWorkdir/.CrystalCache/"
-fi
-
-dbDir="$crystalWorkdir/.CrystalCache/"
-scache_gc "$dbDir" "f"
-
-requestUrl="https://archive.org/download/$CrystalID/$CrystalID.coal5"
-hashFull="$(sha512sum <<< "$requestUrl" | awk '{print $1;}')"
-hashA="${hashFull:0:1}"
-hashB="${hashFull:1:1}"
-hashC="${hashFull:2:1}"
-hashSubdir="$hashA/$hashB/$hashC"
-hashDir="$dbDir/$hashSubdir"
-mkdir -p "$hashDir"
-dbLinkPath="$hashDir/$hashFull"
-checksumName="$dbLinkPath.checksum"
-
-finish() {
-    rm -f "${dbLinkPath:?}.locked"
-}
-trap finish EXIT
-# Don't remove .coal5 file if it fails after this point
-trap 'cat "$crystalWorkdir/NonfinalizedCrystals/$CrystalID" || true; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
-
-[[ -e "$dbLinkPath.locked" ]] && die "This URL cache entry (for a supposedly new crystal) is already in use. This should never happen, and indicates a bug in crystallize."
-
-if [[ -e "$dbLinkPath" ]] || [[ -h "$dbLinkPath" ]]; then
-    die "This URL cache entry (for a supposedly new crystal) already exists. This should never happen, and indicates a bug in crystallize."
-fi
-
-[[ -e "$checksumName" ]] && die "This URL cache entry (for a supposedly new crystal) already has a checksum file. This should never happen, and indicates a bug in crystallize."
-
-echo "locked on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)" > "$dbLinkPath.locked"
-
-requestCount=0
-dbFileDir="$dbDir/ByCount/${requestCount:?}/$hashSubdir"
-dbFilePath="$dbFileDir/$hashFull"
-mkdir -p "$dbFileDir"
-mv "$crystalWorkdir/NonfinalizedCrystals/$CrystalID.coal5" "$dbFilePath"
-sha512sum < "$dbFilePath" | awk '{print $1;}' > "$checksumName"
-printf "%s" "$requestUrl" > "$dbLinkPath.url"
-
-[[ -e "$dbLinkPath" ]] && [[ ! -h "$dbLinkPath" ]] && warn "Cache entry has something that's not a link at the place the link should be ($dbLinkPath). Huh? Removing it." && rm "$dbLinkPath"
-[[ -h "$dbLinkPath" ]] && rm "$dbLinkPath"
-ln -s "$dbFilePath" "$dbLinkPath"
-
-if [[ "$leaveLocked" != "true" ]]; then
-    # Done editing the cache entry, so release the lock
-    rm "$dbLinkPath.locked"
+    if [[ "$leaveLocked" != "true" ]]; then
+        # Done editing the cache entry, so release the lock
+        rm "$dbLinkPath.locked"
+    fi
 fi
 
 echo "Please wait, testing finished item..."
