Update Ember tree

diff --git a/scripts/crystal-search b/scripts/crystal-search
--- a/scripts/crystal-search
+++ b/scripts/crystal-search
@@ -18,13 +18,13 @@ fi
 
 pattern="$1"
 
-cd "${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Crystal\ Index/
+cd "${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Crystal\ Index/ || die "cd failed"
 for file in ./*.deep.idx; do
     if grep -q "$pattern" "$file"; then
         filePassedSingle="0"
         fileName="${file/\.\/}"
         fileNamePrefix="${fileName%\.deep\.idx}"
-        grep -v '^#' "$file" | grep "$pattern" | cut -d ',' -f 5- - | while read line; do
+        grep -v '^#' "$file" | grep "$pattern" | cut -d ',' -f 5- - | while IFS="" read -r line; do
             if [[ "$filePassedSingle" != "1" ]] || [[ "$singleResultOnly" != "true" ]]; then
                 echo "Crystal $fileNamePrefix contains:"
                 echo "    $line"
