Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -128,10 +128,8 @@ while read -r streamRegistryPath; do
                 crystalFilePattern=".*.crystal-data"
                 crystalFilePatternMatches=( $crystalFilePattern )
                 localStoreCrystalName="${crystalFilePatternMatches[0]}"
-                [[ -e "$localStoreCrystalName" ]]; then
-                    die "Crystal info could not be found in the pointer for $packTempDir, so giving up immediately (retrying probably wouldn't help this)."
-                else
-                    localStoreCrystalIdentifier="$(<"$localStoreCrystalName"/identifier)"
+                [[ -e "$localStoreCrystalName" ]] || die "Crystal info could not be found in the pointer for $packTempDir, so giving up immediately (retrying probably wouldn't help this)."
+                localStoreCrystalIdentifier="$(<"$localStoreCrystalName"/identifier)"
                 popd
             fi
         done
