Update Git repository using egup-single

diff --git a/scripts/crystallize b/scripts/crystallize
--- a/scripts/crystallize
+++ b/scripts/crystallize
@@ -25,7 +25,7 @@ trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(p
 finishclean() {
     rm -f "${crystalWorkdir:?}/${CrystalID:?}.coal5"
 }
-trap 'if [[ -e "$crystalWorkdir/$CrystalID" ]]; then cat "$crystalWorkdir/$CrystalID" || true; fi; finishclean; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+trap 'if [[ -e "$crystalWorkdir/Crystals/$CrystalID" ]]; then cat "$crystalWorkdir/Crystals/$CrystalID" || true; fi; finishclean; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
 if [[ ! -e "${EmberLibrary:?}"/CrystalIndex/ ]]; then
     echo "ERROR: Could not find a usable Ember Library directory tree. Nothing done."
@@ -110,47 +110,47 @@ retryUntilSuccess 100 30 5 5 dig +short myip.opendns.com @resolver1.opendns.com 
 
 wait
 
-echo "$0 $*" > "$crystalWorkdir/$CrystalID.cmd"
-pwd > "$crystalWorkdir/$CrystalID.cwd"
+echo "$0 $*" > "$crystalWorkdir/Crystals/$CrystalID.cmd"
+pwd > "$crystalWorkdir/Crystals/$CrystalID.cwd"
 
-crystallize-logsession "$useCustomPassphrase" "$customPassphrase" "$crystalWorkdir/$CrystalID" "$CrystalID" "$@"
+crystallize-logsession "$useCustomPassphrase" "$customPassphrase" "$crystalWorkdir/Crystals/$CrystalID" "$CrystalID" "$@"
 
 if [[ $crystallizeLeavePointer == true ]]; then
     mkdir -p "$crystallizePointerDir"
-    rsync -a --checksum "$crystalWorkdir/$CrystalID.cmd" "$crystalWorkdir/$CrystalID.cwd" "$crystallizePointerDir"/
+    rsync -a --checksum "$crystalWorkdir/Crystals/$CrystalID.cmd" "$crystalWorkdir/Crystals/$CrystalID.cwd" "$crystallizePointerDir"/
 fi
-checkedxz "$crystalWorkdir/$CrystalID" -C sha256 -v -9 -e 2>&1
-checkedxz "$crystalWorkdir/$CrystalID.time-done.warc.gz" -C sha256 -v -9 -e 2>&1
-checkedxz "$crystalWorkdir/$CrystalID.local.idx" -C sha256 -v -9 -e 2>&1
-checkedxz "$crystalWorkdir/$CrystalID.deep.idx" -C sha256 -v -9 -e 2>&1
-checkedxz "$crystalWorkdir/$CrystalID.csum" -C sha256 -v -9 -e 2>&1
-checkedxz "$crystalWorkdir/$CrystalID.forks" -C sha256 -v -9 -e 2>&1
-checkedxz "$crystalWorkdir/$CrystalID.forks-csum" -C sha256 -v -9 -e 2>&1
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.xz"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.time-done.warc.gz.xz"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.local.idx.xz"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.deep.idx.xz"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.csum.xz"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.forks.xz"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.forks-csum.xz"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.cmd"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.cwd"
-gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/$CrystalID".tmp "$crystalWorkdir/$CrystalID.ostype"
-rm "$crystalWorkdir/$CrystalID.csum.xz" "$crystalWorkdir/$CrystalID.local.idx.xz" "$crystalWorkdir/$CrystalID.deep.idx.xz" "$crystalWorkdir/$CrystalID.cmd" "$crystalWorkdir/$CrystalID.cwd" "$crystalWorkdir/$CrystalID.time-done.warc.gz.xz" "$crystalWorkdir/$CrystalID.time-env.warc.gz" "$crystalWorkdir/$CrystalID.time-start.warc.gz" "$crystalWorkdir/$CrystalID.xz" "$crystalWorkdir/$CrystalID.ip.warc.gz" "$crystalWorkdir/$CrystalID.passphrase" "$crystalWorkdir/$CrystalID.ostype" "$crystalWorkdir/$CrystalID.forks.xz" "$crystalWorkdir/$CrystalID.forks-csum.xz"
-mv "$crystalWorkdir/$CrystalID.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-log"
-mv "$crystalWorkdir/$CrystalID.time-done.warc.gz.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-timestamp"
-mv "$crystalWorkdir/$CrystalID.csum.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-csum"
-mv "$crystalWorkdir/$CrystalID.local.idx.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-idx-l"
-mv "$crystalWorkdir/$CrystalID.deep.idx.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-idx-d"
-mv "$crystalWorkdir/$CrystalID.cmd.gpg" "$crystalWorkdir/$CrystalID.coal5-cmd"
-mv "$crystalWorkdir/$CrystalID.cwd.gpg" "$crystalWorkdir/$CrystalID.coal5-cwd"
-mv "$crystalWorkdir/$CrystalID.ostype.gpg" "$crystalWorkdir/$CrystalID.coal5-ostype"
-mv "$crystalWorkdir/$CrystalID.forks.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-forks"
-mv "$crystalWorkdir/$CrystalID.forks-csum.xz.gpg" "$crystalWorkdir/$CrystalID.coal5-forks-csum"
+checkedxz "$crystalWorkdir/Crystals/$CrystalID" -C sha256 -v -9 -e 2>&1
+checkedxz "$crystalWorkdir/Crystals/$CrystalID.time-done.warc.gz" -C sha256 -v -9 -e 2>&1
+checkedxz "$crystalWorkdir/Crystals/$CrystalID.local.idx" -C sha256 -v -9 -e 2>&1
+checkedxz "$crystalWorkdir/Crystals/$CrystalID.deep.idx" -C sha256 -v -9 -e 2>&1
+checkedxz "$crystalWorkdir/Crystals/$CrystalID.csum" -C sha256 -v -9 -e 2>&1
+checkedxz "$crystalWorkdir/Crystals/$CrystalID.forks" -C sha256 -v -9 -e 2>&1
+checkedxz "$crystalWorkdir/Crystals/$CrystalID.forks-csum" -C sha256 -v -9 -e 2>&1
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.xz"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.time-done.warc.gz.xz"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.local.idx.xz"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.deep.idx.xz"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.csum.xz"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.forks.xz"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.forks-csum.xz"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.cmd"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.cwd"
+gpg --yes -c --cipher-algo AES256 --batch --passphrase-file "$crystalWorkdir/Crystals/$CrystalID".tmp "$crystalWorkdir/Crystals/$CrystalID.ostype"
+rm "$crystalWorkdir/Crystals/$CrystalID.csum.xz" "$crystalWorkdir/Crystals/$CrystalID.local.idx.xz" "$crystalWorkdir/Crystals/$CrystalID.deep.idx.xz" "$crystalWorkdir/Crystals/$CrystalID.cmd" "$crystalWorkdir/Crystals/$CrystalID.cwd" "$crystalWorkdir/Crystals/$CrystalID.time-done.warc.gz.xz" "$crystalWorkdir/Crystals/$CrystalID.time-env.warc.gz" "$crystalWorkdir/Crystals/$CrystalID.time-start.warc.gz" "$crystalWorkdir/Crystals/$CrystalID.xz" "$crystalWorkdir/Crystals/$CrystalID.ip.warc.gz" "$crystalWorkdir/Crystals/$CrystalID.passphrase" "$crystalWorkdir/Crystals/$CrystalID.ostype" "$crystalWorkdir/Crystals/$CrystalID.forks.xz" "$crystalWorkdir/Crystals/$CrystalID.forks-csum.xz"
+mv "$crystalWorkdir/Crystals/$CrystalID.xz.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-log"
+mv "$crystalWorkdir/Crystals/$CrystalID.time-done.warc.gz.xz.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-timestamp"
+mv "$crystalWorkdir/Crystals/$CrystalID.csum.xz.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-csum"
+mv "$crystalWorkdir/Crystals/$CrystalID.local.idx.xz.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-idx-l"
+mv "$crystalWorkdir/Crystals/$CrystalID.deep.idx.xz.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-idx-d"
+mv "$crystalWorkdir/Crystals/$CrystalID.cmd.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-cmd"
+mv "$crystalWorkdir/Crystals/$CrystalID.cwd.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-cwd"
+mv "$crystalWorkdir/Crystals/$CrystalID.ostype.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-ostype"
+mv "$crystalWorkdir/Crystals/$CrystalID.forks.xz.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-forks"
+mv "$crystalWorkdir/Crystals/$CrystalID.forks-csum.xz.gpg" "$crystalWorkdir/Crystals/$CrystalID.coal5-forks-csum"
 
-trap 'cat "$crystalWorkdir/$CrystalID" || true; finishclean; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
-ia upload "$CrystalID" --retries=100 --verify --delete "$crystalWorkdir/$CrystalID.coal5-log" "$crystalWorkdir/$CrystalID.coal5-idx-l" "$crystalWorkdir/$CrystalID.coal5-idx-d" "$crystalWorkdir/$CrystalID.coal5-csum" "$crystalWorkdir/$CrystalID.coal5-cmd" "$crystalWorkdir/$CrystalID.coal5-cwd" "$crystalWorkdir/$CrystalID.coal5-ostype" "$crystalWorkdir/$CrystalID.coal5-forks" "$crystalWorkdir/$CrystalID.coal5-forks-csum" 2>&1
-ia upload "$CrystalID" --retries=100 --verify "$crystalWorkdir/$CrystalID.coal5-timestamp" 2>&1
+trap 'cat "$crystalWorkdir/Crystals/$CrystalID" || true; finishclean; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+ia upload "$CrystalID" --retries=100 --verify --delete "$crystalWorkdir/Crystals/$CrystalID.coal5-log" "$crystalWorkdir/Crystals/$CrystalID.coal5-idx-l" "$crystalWorkdir/Crystals/$CrystalID.coal5-idx-d" "$crystalWorkdir/Crystals/$CrystalID.coal5-csum" "$crystalWorkdir/Crystals/$CrystalID.coal5-cmd" "$crystalWorkdir/Crystals/$CrystalID.coal5-cwd" "$crystalWorkdir/Crystals/$CrystalID.coal5-ostype" "$crystalWorkdir/Crystals/$CrystalID.coal5-forks" "$crystalWorkdir/Crystals/$CrystalID.coal5-forks-csum" 2>&1
+ia upload "$CrystalID" --retries=100 --verify "$crystalWorkdir/Crystals/$CrystalID.coal5-timestamp" 2>&1
 
 echo "Please wait..."
 
@@ -181,7 +181,7 @@ until [[ "$getChecksumRetries" -ge 1000 ]]; do
     fi
 done
 
-knownChecksum="$(grep ",stdin" "$crystalWorkdir/$CrystalID.checksums" | awk -F',' '{print $3}')"
+knownChecksum="$(grep ",stdin" "$crystalWorkdir/Crystals/$CrystalID.checksums" | awk -F',' '{print $3}')"
 
 retryUntilSuccess 1000 60 5 5 iasha1 "$CrystalID/$CrystalID.coal5" > /dev/null || die "Number of allowed retries exceeded without success."
 checksumLine="$(retryUntilSuccess 1000 60 5 5 iasha1 "$CrystalID/$CrystalID.coal5")" || die "Number of allowed retries exceeded without success."
@@ -192,7 +192,7 @@ if [[ "$checksumLine" != "$knownChecksum" ]]; then
 fi
 
 # Now, check the local file's checksum again in case it's gotten screwed up in the mean time somehow
-knownChecksum="$(hashdeep -c sha1 -j0 -o fbcpsde < "$crystalWorkdir/$CrystalID.coal5" | grep ",stdin" | awk -F',' '{print $2}')"
+knownChecksum="$(hashdeep -c sha1 -j0 -o fbcpsde < "$crystalWorkdir/Crystals/$CrystalID.coal5" | grep ",stdin" | awk -F',' '{print $2}')"
 if [[ "$checksumLine" != "$knownChecksum" ]]; then
     die "ERROR! Checksum known by Internet Archive $checksumLine does not match new checksum known locally $knownChecksum."
 fi
@@ -217,13 +217,13 @@ fi
 
 echo "Retrieving remote index..."
 
-rm -f "$crystalWorkdir/$CrystalID".json.xz
-{ retryUntilSuccess 100 30 5 5 wget --delete-after --save-headers --output-document - "https://archive.org/metadata/$CrystalID/" > "$crystalWorkdir/$CrystalID.json"; } 2>&1
-checkedxz "$crystalWorkdir/$CrystalID".json -C sha256 -9 -e -v 2>&1
+rm -f "$crystalWorkdir/Crystals/$CrystalID".json.xz
+{ retryUntilSuccess 100 30 5 5 wget --delete-after --save-headers --output-document - "https://archive.org/metadata/$CrystalID/" > "$crystalWorkdir/Crystals/$CrystalID.json"; } 2>&1
+checkedxz "$crystalWorkdir/Crystals/$CrystalID".json -C sha256 -9 -e -v 2>&1
 
-rsync -av --progress --checksum "$crystalWorkdir/$CrystalID.json.xz" "$crystalWorkdir/$CrystalID.checksums" "${EmberLibrary:?}"/CrystalIndex/
+rsync -av --progress --checksum "$crystalWorkdir/Crystals/$CrystalID.json.xz" "$crystalWorkdir/Crystals/$CrystalID.checksums" "${EmberLibrary:?}"/CrystalIndex/
 
-rm "$crystalWorkdir/$CrystalID.json.xz" "$crystalWorkdir/$CrystalID.checksums"
+rm "$crystalWorkdir/Crystals/$CrystalID.json.xz" "$crystalWorkdir/Crystals/$CrystalID.checksums"
 
 # Next section registers the newly created crystal in the CrystalCache so an immediate decrystallize doesn't need to re-download it.
 
@@ -250,7 +250,7 @@ finish() {
 }
 trap finish EXIT
 # Don't remove .coal5 file if it fails after this point
-trap 'cat "$crystalWorkdir/$CrystalID" || true; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+trap 'cat "$crystalWorkdir/Crystals/$CrystalID" || true; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
 [[ -e "$dbLinkPath.locked" ]] && die "This URL cache entry (for a supposedly new crystal) is already in use. This should never happen, and indicates a bug in crystallize."
 
@@ -266,7 +266,7 @@ requestCount=0
 dbFileDir="$dbDir/ByCount/${requestCount:?}/$hashSubdir"
 dbFilePath="$dbFileDir/$hashFull"
 mkdir -p "$dbFileDir"
-mv "$crystalWorkdir/$CrystalID.coal5" "$dbFilePath"
+mv "$crystalWorkdir/Crystals/$CrystalID.coal5" "$dbFilePath"
 sha512sum < "$dbFilePath" | awk '{print $1;}' > "$checksumName"
 printf "%s" "$requestUrl" > "$dbLinkPath.url"
 
@@ -283,8 +283,8 @@ echo "Please wait, testing finished item..."
 testDecrystDir="$(bigTempDir)"
 (
     cd "$testDecrystDir" || die "cd failed"
-    decrystallize --passphrase "$(<"$crystalWorkdir/$CrystalID".tmp)" --lock-override "$CrystalID" 2>&1 || die "Could not decrystallize the finished crystal!"
-    rm "$crystalWorkdir/$CrystalID.tmp"
+    decrystallize --passphrase "$(<"$crystalWorkdir/Crystals/$CrystalID".tmp)" --lock-override "$CrystalID" 2>&1 || die "Could not decrystallize the finished crystal!"
+    rm "$crystalWorkdir/Crystals/$CrystalID.tmp"
 )
 rm -r "${testDecrystDir:?}"
 
@@ -304,7 +304,7 @@ trap - ERR
 if [[ "$keepFiles" != "true" ]]; then
     rm -rf "${CrystallizePaths[@]}"
 fi
-trap 'cat "$crystalWorkdir/$CrystalID" || true; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+trap 'cat "$crystalWorkdir/Crystals/$CrystalID" || true; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 set -o pipefail
 echo "Done cleaning up..."
 
@@ -327,7 +327,7 @@ fi
 chmod -R 644 "${EmberLibrary:?}"/CrystalIndex/
 chmod 755 "${EmberLibrary:?}"/CrystalIndex/
 
-if rm -v "$crystalWorkdir/$CrystalID.coal5-timestamp"; then
+if rm -v "$crystalWorkdir/Crystals/$CrystalID.coal5-timestamp"; then
     #Clear the screen
     printf "\\033c"
 
