Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -98,27 +98,31 @@ shopt -s dotglob
 cbbStreamRegistries="$(<crystal-backup-meta/cbb-index/stream-registries)"
 while read -r streamRegistryPath; do
     if [[ -n "$streamRegistryPath" ]]; then
-        streamRegistryPath="repositories/$streamRegistryPath"
+        streamRegistryFullPath="repositories/$streamRegistryPath"
         streamRegistryRepoName="${streamRegistryPath%%\/*}"
         streamRegistryPathInRepo="${streamRegistryPath#*\/}"
-        if ! [[ -d "$streamRegistryRepoName" ]]; then
+        (
+            cd repositories
+            if ! [[ -d "$streamRegistryRepoName" ]]; then
+                (
+                    mkdir "$streamRegistryRepoName"
+                    cd "$streamRegistryRepoName" || die "Could not cd to newly created directory $(pwd)/$streamRegistryRepoName!"
+                    git init
+                    git config core.sparseCheckout true
+                    git remote add -f origin "$streamRegistryRepoName.git"
+                    echo "$streamRegistryPathInRepo*" > .git/info/sparse-checkout
+                    git checkout "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
+                )
+            fi
             (
-                mkdir "$streamRegistryRepoName"
-                cd "$streamRegistryRepoName" || die "Could not cd to newly created directory $(pwd)/$streamRegistryRepoName!"
-                git init
-                git config core.sparseCheckout true
-                git remote add -f origin "$streamRegistryRepoName.git"
-                echo "$streamRegistryPathInRepo*" > .git/info/sparse-checkout
-                git checkout "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
+                cd "$streamRegistryPath" || die "Could not cd to repository directory $(pwd)/$streamRegistryPath!"
+                git pull origin
             )
-        fi
-        cd "$streamRegistryRepoName" || die "Could not cd to repository directory $(pwd)/$streamRegistryRepoName!"
-        git pull origin
-        cd ..
+        )
         # Go through this sreg and add all the crystals it uses to the index
 
         # Normal remote pack pointers
-        for identFile in "$streamRegistryPath/Packs/"*.identifier; do
+        for identFile in "$streamRegistryFullPath/Packs/"*.identifier; do
             echo "$(<"$identFile")" >> "crystal-backup-meta/cbb-index/items"
             # true # (Skipping ident file since this is disabled right now to make testing faster)
             # FIXME: won't work for packs that don't have a .identifier file (older ones just have a pointer file)
@@ -131,7 +135,7 @@ while read -r streamRegistryPath; do
         # Standard remote pointers [a5e2f296-3085-49c0-8f48-24ea436b7a8b]
         # URL pointers [45baff46-8db7-46f6-aad9-de5f713b02fe]
         shopt -s globstar
-        # for potentialPointer in "$streamRegistryPath"/**; do
+        # for potentialPointer in "$streamRegistryFullPath"/**; do
         #     if [[ -f "$potentialPointer" ]]; then
         #         typeSignature="$(head -c 36 "$potentialPointer" | tr -d '\0')"
         #         if [[ "$typeSignature" == "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]]; then # Standard remote pointer
