Update Ember tree

diff --git a/scripts/crystal-bulk-backup b/scripts/crystal-bulk-backup
--- a/scripts/crystal-bulk-backup
+++ b/scripts/crystal-bulk-backup
@@ -106,7 +106,7 @@ while read -r streamRegistryPath; do
         )
         # Go through this sreg and add all the crystals it uses to the index
 
-        pushd "$streamRegistryFullPath/Packs/" || die "Could not pushd to Packs directory!"
+        spushd "$streamRegistryFullPath/Packs/" || die "Could not pushd to Packs directory!"
 
         # Normal remote pack pointers
         echo "Getting identifiers for packs in $streamRegistryPath"
@@ -121,7 +121,7 @@ while read -r streamRegistryPath; do
                 # This pack doesn't have a .identifier file, so it needs to be extracted separately
                 packTempDir="$(tempDir)"
                 packDir="$PWD"
-                pushd "$packTempDir" || die "Could not pushd to $packTempDir!"
+                spushd "$packTempDir" || die "Could not pushd to $packTempDir!"
                 unxz --stdout - < "$packDir/$pointerFile" | tar -xf -
                 # MAINTENANCE: Code copied and tweaked from sreg_read_stream
                 crystalFilePattern=".*.crystal-data"
@@ -134,12 +134,12 @@ while read -r streamRegistryPath; do
                 [[ -e "$localStoreCrystalName" ]] || die "Crystal info could not be found in the pointer for $pointerFile, so giving up immediately (retrying probably wouldn't help this)."
                 echo "$(<"$localStoreCrystalName"/identifier)" >> "$backupLocation/crystal-backup-meta/cbb-index/items"
                 touch "$backupLocation/crystal-backup-meta/cbb-index/items.packs-done/${pointerFile%.bundle.pointer}"
-                popd || die "Could not popd!"
+                spopd || die "Could not popd!"
                 rm -r "$packTempDir"
             fi
         done
 
-        popd || die "Could not popd!"
+        spopd || die "Could not popd!"
 
         # TODO: Not implemented
         # Remote pack pointers, with pointer data in the pointer [209fcfdf-d1ad-4345-8ef7-1fdc2d583d49]
