Update Git repository using egup-single

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -89,7 +89,7 @@ decrystInner() (
         fi
     }
 
-    # FIXME: Why the actual fuck does execution continue past the next line when tar exits with a nonzero exit status?! The ERR trap gets printed out correctly when running "trap" with no arguments right after it, but for some reason doesn't get called here. Weird.
+    # FIXME: Why does execution continue past the next line when tar exits with a nonzero exit status?! The ERR trap gets printed out correctly when running "trap" with no arguments right after it, but for some reason doesn't get called here. Weird.
     fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5" "$lockOverride" | pv -tparbIfei 0.1 -s "$crystalXzFileSize" | gpg --yes --batch --passphrase-file "$tempId.tmp" - | unxz --stdout - | tar -xvf - -C "$tempId/" || decrystallizeNoDieOnMac
     #trap
 
@@ -103,6 +103,7 @@ decrystInner() (
         cd "$tempDecrystForksDir" || die
         mkdir ".forks"
 
+        if version_gt "$knownCrystalCrystallizeVersion" "3.1.2.5.13.61"; then
         trap - ERR
         fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5-forks" | pv -tparbIfei 0.1 | gpg --yes --batch --passphrase-file "$tempIdAbspath.tmp" - | unxz --stdout - | tar -xvf - -C ".forks"
         forkFetchStatus="$?"
@@ -121,6 +122,8 @@ decrystInner() (
                 # This crystal was made by a version that supports split fork storage
                 die "Error retrieving split forks for this crystal!"
             fi
+        fi
+        else
             warn "(Couldn't retrieve split forks file for this crystal as the version of crystallize it was created using is too old.)"
         fi
 
