Update Ember tree

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -95,6 +95,7 @@ decrystInner() (
     else
         metadata="$(fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID"_meta.xml)"
         regex='<subject>Uploaded using Crystallize ([0-9\.]+)<\/subject>'
+        [[ -n "$metadata" ]] || die "Could not get metadata for this crystal."
         crystalCrystallizeVersion=""
         if [[ "$metadata" =~ $regex ]]; then
             crystalCrystallizeVersion="${BASH_REMATCH[1]}"
