Update Git repository using egup-single

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -191,14 +191,14 @@ decrystInner() (
     if [[ "$exitStatus" == "0" ]]; then
         mkdir "$tempId.tempDir"
         # This code talking about "findfail" before and after the csum is broken, but I can't tell out what it's supposed to do to fix it. Formerly the outer subshells had || die after them instead of || true.
-        (
-            cd "$tempId"
-            findfail="$(tempFile)"
-            rm "$findfail"
-            find . -name "$CrystalID"'*' -not -name "$CrystalID.ostype" -not -name "$CrystalID.forks" -not -name "$CrystalID.forks-csum" -exec bash -c 'trap '\''touch "$0"'\'' ERR; dir="$(dirname "$1")"; mkdir -p "../'"$tempId"'.tempDir/$dir/"; mv "$1" "../'"$tempId"'.tempDir/$dir/"' "$findfail" {} \; || die
-            [[ -e "$findfail" ]] && die
-            true
-        ) || true
+        #(
+        #    cd "$tempId"
+        #    findfail="$(tempFile)"
+        #    rm "$findfail"
+        #    find . -name "$CrystalID"'*' -not -name "$CrystalID.ostype" -not -name "$CrystalID.forks" -not -name "$CrystalID.forks-csum" -exec bash -c 'trap '\''touch "$0"'\'' ERR; dir="$(dirname "$1")"; mkdir -p "../'"$tempId"'.tempDir/$dir/"; mv "$1" "../'"$tempId"'.tempDir/$dir/"' "$findfail" {} \; || die
+        #    [[ -e "$findfail" ]] && die
+        #    true
+        #) || true
 
         (
             cd "$tempId"
@@ -206,14 +206,14 @@ decrystInner() (
             csum --check ./* "../$tempId.csum" || die
         ) || die
 
-        (
-            cd "$tempId.tempDir"
-            findfail="$(tempFile)"
-            rm "$findfail"
-            find . -name "$CrystalID"'*' -exec bash -c 'trap '\''touch "$0"'\'' ERR; dir="$(dirname "$1")"; mv "$1" "../'"$tempId"'/$dir/"' "$findfail" {} \; || die
-            [[ -e "$findfail" ]] && die
-            true
-        ) || true
+        #(
+        #    cd "$tempId.tempDir"
+        #    findfail="$(tempFile)"
+        #    rm "$findfail"
+        #    find . -name "$CrystalID"'*' -exec bash -c 'trap '\''touch "$0"'\'' ERR; dir="$(dirname "$1")"; mv "$1" "../'"$tempId"'/$dir/"' "$findfail" {} \; || die
+        #    [[ -e "$findfail" ]] && die
+        #    true
+        #) || true
         rm -r "${tempId:?}.tempDir"
     else
         [[ -n $knownCrystalCrystallizeVersion ]] || getCrystalVersion
