Update Git repository using egup-single

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -103,26 +103,26 @@ decrystInner() (
         cd "$tempDecrystForksDir" || die
         mkdir ".forks"
 
+        [[ -n $knownCrystalCrystallizeVersion ]] || getCrystalVersion
         if version_gt "$knownCrystalCrystallizeVersion" "3.1.2.5.13.61"; then
-        trap - ERR
-        fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5-forks" | pv -tparbIfei 0.1 | gpg --yes --batch --passphrase-file "$tempIdAbspath.tmp" - | unxz --stdout - | tar -xvf - -C ".forks"
-        forkFetchStatus="$?"
-        fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5-forks-csum" | pv -tparbIfei 0.1 | gpg --yes --batch --passphrase-file "$tempIdAbspath.tmp" - | unxz --stdout - > ".forks-csum"
-        forkCsumFetchStatus="$?"
-        trap 'rm -r "${tempDecrystForksDir:?}"; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+            # This crystal was made by a version that supports split fork storage
+            trap - ERR
+            fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5-forks" | pv -tparbIfei 0.1 | gpg --yes --batch --passphrase-file "$tempIdAbspath.tmp" - | unxz --stdout - | tar -xvf - -C ".forks"
+            forkFetchStatus="$?"
+            fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5-forks-csum" | pv -tparbIfei 0.1 | gpg --yes --batch --passphrase-file "$tempIdAbspath.tmp" - | unxz --stdout - > ".forks-csum"
+            forkCsumFetchStatus="$?"
+            trap 'rm -r "${tempDecrystForksDir:?}"; die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
 
-        if [[ "$forkFetchStatus" == "0" ]] && [[ "$forkCsumFetchStatus" == "0" ]]; then
-            (
-                cd ".forks" || die "cd failed"
-                csum --check ./* "../.forks-csum" || die "csum reported an error for split forks"
-            ) || die "Failed split forks checksum"
-        else
-            [[ -n $knownCrystalCrystallizeVersion ]] || getCrystalVersion
-            if version_gt "$knownCrystalCrystallizeVersion" "3.1.2.5.13.61"; then
-                # This crystal was made by a version that supports split fork storage
-                die "Error retrieving split forks for this crystal!"
+            if [[ "$forkFetchStatus" == "0" ]] && [[ "$forkCsumFetchStatus" == "0" ]]; then
+                (
+                    cd ".forks" || die "cd failed"
+                    csum --check ./* "../.forks-csum" || die "csum reported an error for split forks"
+                ) || die "Failed split forks checksum"
+            else
+                if version_gt "$knownCrystalCrystallizeVersion" "3.1.2.5.13.61"; then
+                    die "Error retrieving split forks for this crystal!"
+                fi
             fi
-        fi
         else
             warn "(Couldn't retrieve split forks file for this crystal as the version of crystallize it was created using is too old.)"
         fi
