Update Git repository using egup-single

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -163,7 +163,10 @@ decrystInner() (
         if [[ "$OSTYPE" == darwin* ]]; then
             splitForksTarWanted="gtar"
         fi
-        find ".forks" -type f -not -name '06968986-7c96-406f-b7b2-a90fe40293bd' -exec bash -c "$splitForksTarWanted"' -xvf - -C "$1/" < "$0"' {} "$tempIdAbspath" \;
+        findfail="$(tempFile)"
+        rm "$findfail"
+        find ".forks" -type f -not -name '06968986-7c96-406f-b7b2-a90fe40293bd' -exec bash -c 'trap '\''touch "$0" ERR'\''; '"$splitForksTarWanted"' -xvf - -C "$1/" < "$1"' "$findfail" {} "$tempIdAbspath" \;
+        [[ -e "$findfail" ]] && die
     ) || die
     rm -r "$tempDecrystForksDir"
 
