Update Git repository using egup-single

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -79,11 +79,11 @@ if [[ "true" == "$offline" ]]; then
 fi
 
 crystalXzFileSize=1
-if [[ -t 1 ]] && [[ "false" == "$offline" ]]; then
-    # used for pv progress indicator.
-    crystalXzFileSize="$(retryUntilSuccess 100 30 5 5 curl -sIL "https://archive.org/download/$CrystalID/$CrystalID.coal5" | grep Content-Length | awk '{print $2}')" || warn "Couldn't get compressed file size"
-    crystalXzFileSize="${crystalXzFileSize::-1}"
-fi
+#if [[ -t 1 ]] && [[ "false" == "$offline" ]]; then
+#    # used for pv progress indicator.
+#    crystalXzFileSize="$(retryUntilSuccess 100 30 5 5 curl -sIL "https://archive.org/download/$CrystalID/$CrystalID.coal5" | grep Content-Length | awk '{print $2}')" || warn "Couldn't get compressed file size"
+#    crystalXzFileSize="${crystalXzFileSize::-1}"
+#fi
 
 if [[ "$useCustomPassphrase" != "true" ]]; then
     crystallizePassphrase="$(crystallize-getconf Passphrase)"
