Update Ember tree

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -43,12 +43,20 @@ crystalWorkdir="$(crystallize-getconf WorkDirectory)"
 if ! [[ -e "$crystalWorkdir/.CrystalCache/" ]]; then
     fcache_init "$crystalWorkdir/.CrystalCache/" 5000000000
 fi
+# This should be set, but set it again just in case
+set -o pipefail
+
+# Try to catch the case of the pipeline fails and exits before wait gets called
+set -e
+
 fcache_request "$crystalWorkdir/.CrystalCache/" "https://archive.org/download/$CrystalID/$CrystalID.coal5" | pv -tparbIfei 0.1 -s "$crystalXzFileSize" | gpg --yes --batch --passphrase-file "$tempId.tmp" - | unxz --stdout - | tar -xvf - -C "$tempId/" &
 
 wget -qO - "https://archive.org/download/$CrystalID/$CrystalID.coal5-cwd" | gpg --yes --batch --passphrase-file "$tempId.tmp" - > "$tempId.cwd"
 crystalPath="$(< "$tempId.cwd")"
 
-wait
+wait || die "wait returned nonzero exit status"
+
+set +e
 
 destination="$tempId in "
 if [[ "$decrystallizeHere" == "true" ]]; then
diff --git a/scripts/fcache_request b/scripts/fcache_request
--- a/scripts/fcache_request
+++ b/scripts/fcache_request
@@ -20,8 +20,14 @@ hashSubdir="$hashA/$hashB/$hashC"
 hashDir="$dbDir/$hashSubdir"
 mkdir -p "$hashDir"
 dbLinkPath="$hashDir/$hashFull"
-checksumName="$dbLinkPath.checksum"
-if [[ ! -h "$dbLinkPath" ]] || [[ ! -s "$(readlink "$dbLinkPath")" ]]; then
+checksumName="${dbLinkPath:?}.checksum"
+csAvail="false"
+[[ -e "$checksumName" ]] && csAvail="true"
+tempResolvedFileName="$(readlink "$dbLinkPath")"
+if [[ ! -h "$dbLinkPath" ]] || [[ ! -s "$tempResolvedFileName" ]] || [[ "$csAvail" == "false" ]]; then
+    if [[ -f "$tempResolvedFileName" ]]; then
+        rm "$tempResolvedFileName"
+    fi
     # Item is not in the cache, so add it
     if ! [[ -f "$dbLinkPath" ]]; then
         # Never seen this item before, so set the requestCount
@@ -46,6 +52,7 @@ if [[ ! -h "$dbLinkPath" ]] || [[ ! -s "$(readlink "$dbLinkPath")" ]]; then
 fi
 dbFilePath="$(readlink -e "$dbLinkPath")"
 # Check that the data were retrieved successfully
+[[ -e "$checksumName" ]] || die "Checksum file for requested item is missing!"
 knownChecksum="$(<"$checksumName")"
 itemChecksum="$(sha512sum < "$dbLinkPath" | awk '{print $1;}')"
 if [[ "$itemChecksum" != "$knownChecksum" ]]; then
