Update Ember tree

diff --git a/scripts/decrystallize-logsession b/scripts/decrystallize-logsession
--- a/scripts/decrystallize-logsession
+++ b/scripts/decrystallize-logsession
@@ -111,7 +111,12 @@ mv -v "./$CrystalLogID.local.idx" "./$CrystalLogID/$CrystalID.local.idx"
 mv -v "./$CrystalLogID.deep.idx" "./$CrystalLogID/$CrystalID.deep.idx"
 
 if [[ $decrystallizeEasyUse == true ]]; then
-    mv "$CrystalLogID/$CrystalID" ~/Decrystallized/
+    set +e
+    echo "Ok if next command fails"
+    mv -v "~/Decrystallized/$CrystalID" "~/Decrystallized/$CrystalLogID.dec"
+    set -e
+    echo "Not ok if next commands fail"
+    mv -v "$CrystalLogID/$CrystalID" ~/Decrystallized/
     echo "Moved files for easy use"
 fi
 
