Update Git repository using egup-single

diff --git a/scripts/decrystallize b/scripts/decrystallize
--- a/scripts/decrystallize
+++ b/scripts/decrystallize
@@ -55,7 +55,7 @@ mkdir "$tempId"
 
 crystalXzFileSize=1
 if [[ -t 1 ]]; then
-    crystalXzFileSize="$(curl -sIL "https://archive.org/download/$CrystalID/$CrystalID.coal5" | grep Content-Length | awk '{print $2}')" || warn "Couldn't get compressed file size"
+    crystalXzFileSize="$(retryUntilSuccess 100 30 5 5 curl -sIL "https://archive.org/download/$CrystalID/$CrystalID.coal5" | grep Content-Length | awk '{print $2}')" || warn "Couldn't get compressed file size"
     crystalXzFileSize="${crystalXzFileSize::-1}"
 fi
 
