Update Ember tree

diff --git a/scripts/depbz b/scripts/depbz
--- a/scripts/depbz
+++ b/scripts/depbz
@@ -11,12 +11,27 @@ depbzHome="$(</tmp/depbzHome)"
 
 finish() {
     [[ -e "/tmp/depbzHome" ]] && rm "/tmp/depbzHome"
+    trap - ERR
+    (
+        cd "/${crystalWorkdir:?}/" || die
+        if [[ -e "/$crystalWorkdir/${streamId:?}" ]]; then
+            rm -r "/$crystalWorkdir/${streamId:?}"
+        fi
+    )
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} while finishing $hashFull."' ERR
 }
 trap finish EXIT
 
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 shopt -s extglob
+
+crystalWorkdir="$(crystallize-getconf WorkDirectory)"
+cd "$crystalWorkdir" || exit 1
+streamId="sreg_read_stream-$(date-uuid)"
+mkdir -p "$streamId"
+
+streamDir="$crystalWorkdir/$streamId"
 
 useCustomPassphrase="false"
 crystallizePassphrase=""
@@ -46,7 +61,8 @@ if [[ "$encrypted" == "true" ]]; then
         [[ -e "$passphraseLocation" && ! -d "$passphraseLocation" ]] || die "Could not find passphrase file, expected to be at $passphraseLocation. Please create it, or specify a passphrase using the --passphrase option."
         crystallizePassphrase="$(<~/.pbz)"
     fi
-    
+    echo "$crystallizePassphrase" > "$streamDir/passphrase"
+    cp "./Packed-$date.pbze" "$streamDir/.tmp-$date.gpg"
     os.system('mv -v ./Packed-'+date+'.pbze .tmp-'+date+'.gpg')
     os.system('gpg --yes --batch --passphrase-file ~/.pbz ./.tmp-'+date+'.gpg')
     os.system('rm -v ./.tmp-'+date+'.gpg')
