Update Ember tree

diff --git a/scripts/dequicklify b/scripts/dequicklify
--- a/scripts/dequicklify
+++ b/scripts/dequicklify
@@ -1,6 +1,9 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# shellcheck disable=SC1091
+source ember_bash_setup &> /dev/null
+#set -x
 
-#Usage: dequicklify [--no-trim-extensions|--trim-extensions] <URL>
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 shopt -s extglob
 
@@ -8,12 +11,12 @@ shopt -s extglob
 CrystalAddress="${1#https://archive.org/@(details|download)/}"
 #Remove trailing path(s) from identifier
 CrystalAddress="${CrystalAddress%%/*}"
-if [ "$2" != "--no-trim-extensions" ]; then
+if [[ "$2" != "--no-trim-extensions" ]]; then
     #Remove filename extensions
     CrystalAddress="${CrystalAddress%\.coal5*}"
 fi
 
-if [ "$CrystalAddress" == "" ]; then
+if [[ "$CrystalAddress" == "" ]]; then
     echo "Please specify an item to retrieve."
     exit 1
 fi
diff --git a/scripts/quickliquid b/scripts/quickliquid
--- a/scripts/quickliquid
+++ b/scripts/quickliquid
@@ -1,14 +1,15 @@
-#!/bin/bash
+#!/usr/bin/env bash
+# shellcheck disable=SC1091
+source ember_bash_setup &> /dev/null
+#set -x
 
-#Usage: quickliquid <files>
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+
+crystallizeVersion="$(crystallize-getconf 'crystallizeVersion')"
 
 IUIDENTIFIER="Liquid-"$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")-$(python -c 'import uuid; print str(uuid.uuid4())')
 
-crystallizeVersionA=$(sed '4q;d' /usr/local/bin/crystallize)
-crystallizeVersionB=${crystallizeVersionA%\'*}
-crystallizeVersion=${crystallizeVersionB##*\'}
-
-crystalTitle=$(crystallize-getconf 'InstallationIdentifier')
+crystalTitle="$(crystallize-getconf 'InstallationIdentifier')"
 
 ia upload "$IUIDENTIFIER" --verify --metadata="subject:Uploaded using quickliquid for Crystallize $crystallizeVersion" --metadata="subject:9F227910-A541-11E5-8BD3-7B584224FF49" --metadata="subject:$crystalTitle" "$@"
 
