Update Git repository using egup-single

diff --git a/scripts/egup-single b/scripts/egup-single
--- a/scripts/egup-single
+++ b/scripts/egup-single
@@ -85,10 +85,14 @@ git add -A || die "Error adding changes."
 git add -A . || die "Error adding changes."
 git commit -a -m "$commitMessage" || echo "(Note: Repository appears to have no changes to commit.)"
 if [[ -f .egup.hooks ]]; then
-    echo "Beginning running hooks..."
-    ./.egup.hooks || warn "WARNING! pre-build-hooks failed; continuing anyway."
-    echo "Done running hooks."
-    git commit -a -m "[egup] Update hooks$commitMessageAppendable" || true #It's ok if this fails — it probably means there is nothing to commit, and the user was already notified by saying "no changes to commit" earlier.
+    if [[ "$noHooks" == "true" ]]; then
+        warn "Skipping hooks because --no-hooks was specified."
+    else
+        echo "Beginning running hooks..."
+        ./.egup.hooks || warn "WARNING! pre-build-hooks failed; continuing anyway."
+        echo "Done running hooks."
+        git commit -a -m "[egup] Update hooks$commitMessageAppendable" || true #It's ok if this fails — it probably means there is nothing to commit, and the user was already notified by saying "no changes to commit" earlier.
+    fi
 fi
 
 status=""
