Update Ember tree

diff --git a/scripts/ember_bash_setup b/scripts/ember_bash_setup
--- a/scripts/ember_bash_setup
+++ b/scripts/ember_bash_setup
@@ -90,3 +90,16 @@ function preadconf() {
     readconf "$@"
     print "${readconfValue[0]}"
 }
+
+function ia () {
+    # Retry wrapper for ia since it usually blows up when it hits an error
+    retryCount = 0
+    succeded = false
+    while [[ !succeded && retryCount < 30 ]]; do
+        ia "$@" && succeded = true
+        retryCount = $(( retryCount + 1 ))
+    done
+    if [[ retryCount >= 30 ]]; then
+        exit 1
+    fi
+}
