blah

diff --git a/scripts/fcache_init b/scripts/fcache_init
--- a/scripts/fcache_init
+++ b/scripts/fcache_init
@@ -6,7 +6,7 @@ source "$(which ember_bash_setup)" &> /dev/null
 # If the cache directory already exists, the current size limit will override the one provided as an argument.
 
 [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
-trap 'error-die "${BASH_SOURCE} line ${LINENO}"' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 if [ -e "$1"/.fcache.limit ]; then
     exit 0
diff --git a/scripts/scache_read_stream b/scripts/scache_read_stream
--- a/scripts/scache_read_stream
+++ b/scripts/scache_read_stream
@@ -5,7 +5,7 @@ source "$(which ember_bash_setup)" &> /dev/null
 
 # TODO: Does this really need root privileges?
 [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
-trap 'error-die "${BASH_SOURCE} line ${LINENO}"' ERR
+trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 
 if [[ "--disallow-hash-pointer" == "$1" ]]; then
     disallowHashPointer="true"
