Update Ember tree

diff --git a/scripts/fcache_request b/scripts/fcache_request
--- a/scripts/fcache_request
+++ b/scripts/fcache_request
@@ -44,7 +44,6 @@ csAvail="false"
 [[ -e "$checksumName" ]] && csAvail="true"
 tempResolvedFileName="$(readlink "$dbLinkPath")" || true # It's totally ok if this fails.
 if [[ ! -h "$dbLinkPath" ]] || [[ ! -s "$tempResolvedFileName" ]] || [[ "$csAvail" == "false" ]]; then
-
     # Only lock the cache entry while we're editing it
     touch "$dbLinkPath.locked"
 
@@ -65,10 +64,14 @@ if [[ ! -h "$dbLinkPath" ]] || [[ ! -s "$tempResolvedFileName" ]] || [[ "$csAvai
     dbFileDir="$dbDir/ByCount/${requestCount:?}/$hashSubdir"
     dbFilePath="$dbFileDir/$hashFull"
     mkdir -p "$dbFileDir"
-    wget -t 150 -qcO "$dbFilePath" "$requestUrl"
+    if [[ -e "$dbFilePath" ]]; then
+        warn "$dbFilePath already seems to exist. Huh? Removing it."
+        rm "$dbFilePath"
+    fi
+    wget -t 150 -qO "$dbFilePath" "$requestUrl"
     sha512sum < "$dbFilePath" | awk '{print $1;}' > "$checksumName"
     printf "%s" "$requestUrl" > "$dbLinkPath.url"
-    if [[ -h "$dbLinkPath" ]]; then
+    if [[ -e "$dbLinkPath" ]] || [[ -h "$dbLinkPath" ]]; then
         rm "$dbLinkPath"
     fi
     ln -s "$dbFilePath" "$dbLinkPath"
@@ -86,9 +89,12 @@ if [[ "$itemChecksum" != "$knownChecksum" ]]; then
     die "File did not match what its checksum should be!"
 fi
 # First, make sure the link is good and fix it up if it's not.
-if ! [[ -e "$dbFilePath" ]]; then
+if ! [[ -f "$dbFilePath" ]]; then
     find "$dbDir/ByCount" -mindepth 4 -maxdepth 4 -type d -name "$hashFull" -exec ln -sf {} "$dbLinkPath" \;
     dbFilePath="$(readlink -e "$dbLinkPath")"
+fi
+if ! [[ -f "$dbFilePath" ]]; then
+    die "Could not find the cache file, despite there being a link to it!"
 fi
 dbFileOldPath="$dbFilePath"
 dbFileDir="$(dirname "$dbFilePath")"
diff --git a/scripts/localstorecache_request b/scripts/localstorecache_request
--- a/scripts/localstorecache_request
+++ b/scripts/localstorecache_request
@@ -95,7 +95,7 @@ if [[ ! -h "$dbLinkPath" ]] || [[ ! -d "$oldFilePath" ]] || [[ ! -d "$cacheEntry
         decrystallize --passphrase "$(sregi_get_passphrase "$sregDir")" "$crystalIdentifier" --here &> /dev/null
         mv ./* "$dbFilePath"
     )
-    if [[ -h "$dbLinkPath" ]]; then
+    if [[ -e "$dbLinkPath" ]] || [[ -h "$dbLinkPath" ]]; then
         rm "$dbLinkPath"
     fi
     ln -s "$dbFilePath" "$dbLinkPath"
@@ -105,9 +105,12 @@ if [[ ! -h "$dbLinkPath" ]] || [[ ! -d "$oldFilePath" ]] || [[ ! -d "$cacheEntry
 fi
 dbFilePath="$(readlink -e "$dbLinkPath")"
 # First, make sure the link is good and fix it up if it's not.
-if ! [[ -e "$dbFilePath" ]]; then
+if ! [[ -d "$dbFilePath" ]]; then
     find "$dbDir/ByCount" -mindepth 5 -maxdepth 5 -type d -name "$hashFull" -exec ln -sf {} "$dbLinkPath" \;
     dbFilePath="$(readlink -e "$dbLinkPath")"
+fi
+if ! [[ -d "$dbFilePath" ]]; then
+    die "Could not find the cache file, despite there being a link to it!"
 fi
 dbFileOldPath="$dbFilePath"
 dbFileDir="$(dirname "$dbFilePath")"
diff --git a/scripts/sreg_read_stream b/scripts/sreg_read_stream
--- a/scripts/sreg_read_stream
+++ b/scripts/sreg_read_stream
@@ -129,7 +129,6 @@ mkdir "$streamId"
         fi
         numRetries=$(( numRetries - 1 ))
         if [[ ! -h "$dbLinkPath" ]] || [[ ! -f "$(readlink "$dbLinkPath")" ]] || [[ "$skipCache" == "true" ]]; then
-
             # Only lock the cache entry while we're editing it
             touch "$dbLinkPath.locked"
 
@@ -250,7 +249,7 @@ mkdir "$streamId"
             fi
             [[ -e "$dbFilePath" ]] || xz --stdout -0 "$streamId.out" > "$dbFilePath"
             rm "$streamId.out"
-            if [[ -e "$dbLinkPath" ]]; then
+            if [[ -e "$dbLinkPath" ]] || [[ -h "$dbLinkPath" ]]; then
                 rm "$dbLinkPath"
             fi
             ln -s "$dbFilePath" "$dbLinkPath"
@@ -263,6 +262,9 @@ mkdir "$streamId"
         if ! [[ -f "$dbFilePath" ]]; then
             find "$cacheDbDir/ByCount" -mindepth 5 -maxdepth 5 -type f -name "$hashFull" -exec ln -sf {} "$dbLinkPath" \;
             dbFilePath="$(readlink -e "$dbLinkPath")"
+        fi
+        if ! [[ -e "$dbFilePath" ]]; then
+            die "Could not find the cache file, despite there being a link to it!"
         fi
         dbFileOldPath="$dbFilePath"
         dbFileDir="$(dirname "$dbFilePath")"
