Update Ember tree

diff --git a/scripts/fcache_request b/scripts/fcache_request
--- a/scripts/fcache_request
+++ b/scripts/fcache_request
@@ -23,7 +23,7 @@ dbLinkPath="$hashDir/$hashFull"
 checksumName="${dbLinkPath:?}.checksum"
 csAvail="false"
 [[ -e "$checksumName" ]] && csAvail="true"
-tempResolvedFileName="$(readlink "$dbLinkPath")"
+tempResolvedFileName="$(readlink "$dbLinkPath")" || true # It's totally ok if this fails.
 if [[ ! -h "$dbLinkPath" ]] || [[ ! -s "$tempResolvedFileName" ]] || [[ "$csAvail" == "false" ]]; then
     if [[ -f "$tempResolvedFileName" ]]; then
         rm "$tempResolvedFileName"
