Update Ember tree

diff --git a/scripts/localstorecache_request b/scripts/localstorecache_request
--- a/scripts/localstorecache_request
+++ b/scripts/localstorecache_request
@@ -20,7 +20,7 @@ hashC="${hashFull:2:1}"
 hashSubdir="$hashA/$hashB/$hashC"
 
 # Clean up if there's an error to avoid leaving a broken cache entry
-trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "${dbLinkPath:?}" "$(readlink -e "$dbLinkPath")"' ERR
 
 scache_gc "$dbDir" "localstore"
 
@@ -29,7 +29,7 @@ mkdir -p "$hashDir"
 dbLinkPath="$hashDir/$hashFull"
 trap - ERR
 oldFilePath="$(readlink "$dbLinkPath")"
-trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "$dbLinkPath" "$(readlink -e "$dbLinkPath")"' ERR
+trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -rf "${dbLinkPath:?}" "$(readlink -e "$dbLinkPath")"' ERR
 cacheEntryFileList=("$oldFilePath"/scache-*.LocalStore)
 if [[ ! -h "$dbLinkPath" ]] || [[ ! -f "$oldFilePath" ]] || [[ ! -d "${cacheEntryFileList[0]}" ]]; then
     # Item is not in the cache, so add it
@@ -41,11 +41,11 @@ if [[ ! -h "$dbLinkPath" ]] || [[ ! -f "$oldFilePath" ]] || [[ ! -d "${cacheEntr
         requestCount=1
     else
         requestCount="$(<"$dbLinkPath")"
-        rm "$dbLinkPath"
+        rm "${dbLinkPath:?}"
     fi
     dbFileDir="$dbDir/ByCount/$requestCount/$hashSubdir"
     dbFilePath="$dbFileDir/$hashFull"
-    rm -rf "$dbFilePath"
+    rm -rf "${dbFilePath:?}"
     mkdir -p "$dbFilePath"
     tempDirectoryName="$crystalWorkdir/localstorecache-request-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
     mkdir -p "$tempDirectoryName"
@@ -55,7 +55,7 @@ if [[ ! -h "$dbLinkPath" ]] || [[ ! -f "$oldFilePath" ]] || [[ ! -d "${cacheEntr
         mv ./* "$dbFilePath"
     )
     if [[ -h "$dbLinkPath" ]]; then
-        rm "$dbLinkPath"
+        rm "${dbLinkPath:?}"
     fi
     ln -s "$dbFilePath" "$dbLinkPath"
 fi
@@ -75,14 +75,14 @@ requestCount=$(( oldCount + 1 ))
 dbFileDir="$dbDir/ByCount/$requestCount/$hashSubdir"
 dbFilePath="$dbFileDir/$hashFull"
 mkdir -p "$dbFileDir"
-rm -rf "$dbFilePath"
+rm -rf "${dbFilePath:?}"
 mv "$dbFileOldPath" "$dbFilePath"
-rm "$dbLinkPath"
+rm "${dbLinkPath:?}"
 ln -s "$dbFilePath" "$dbLinkPath"
 # Return the data to the caller
 echo "$dbLinkPath"
 # Clean up empty directories
 find "$dbDir" -type d -not -name "ByCount" -empty -delete
 if [[ -d "$tempDirectoryName" ]]; then
-    rm -r "$tempDirectoryName"
+    rm -r "${tempDirectoryName:?}"
 fi
