blah

diff --git a/scripts/scache_verify_entry b/scripts/scache_verify_entry
--- a/scripts/scache_verify_entry
+++ b/scripts/scache_verify_entry
@@ -1,19 +1,39 @@
 #!/bin/bash
 source "$(which ember_bash_setup)" &> /dev/null
 
-# Accepts an integer and a pointer as an argument, and returns a success status if the data corresponding to the pointer can be read. If it fails, it moves the pointer that failed validation aside. The integer first argument is the number of times to retry if the retrieval fails.
+# Accepts an integer and a pointer as an argument, and returns a success status if the data corresponding to the pointer can be read. If it fails, it moves the pointer that failed validation aside. The integer first argument is the number of times to retry if the retrieval fails. The optional third argument is a filename to a file to be used for tracking progress in an enclosing process.
 
 [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
 trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
 #set -x
 
+fsckStatusFile="$3"
 numRetries="$1"
 shift
 knownHash="$(basename "$1")"
 #echo "Started verifying stream cache database entry $knownHash."
 recoveredHash="$(scache_read_stream --disallow-hash-pointer < "$1" | sha512sum | awk '{print $1;}')"
 if [[ "$knownHash" == "$recoveredHash" ]]; then
-    echo "Verified stream cache database entry $knownHash."
+    if [ -n "$fsckStatusFile" ]; then
+        numberExpected="$(<"$fsckStatusFile")"
+        numberProcessedFile="$fsckStatusFile.done"
+        incrementProcessedCounter() {
+            if ! [ -f "$numberProcessedFile" ]; then
+                numberProcessed="1"
+            else
+                numberProcessed="$(<"$numberProcessedFile")"
+                numberProcessed=$(( numberProcessed + 1 ))
+            fi
+            echo "$numberProcessed" > "$numberProcessedFile"
+            if [[ "$numberExpected" == "0" ]]; then
+                numberExpected="-1"
+            fi
+            numberProcessedPercentage="$(printf "%.3f\n" "$(bc -l <<< "($numberProcessed / $numberExpected)")")"
+            echo "Verified stream cache database entry $knownHash: finished #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
+        }
+    else
+        echo "Verified stream cache database entry $knownHash."
+    fi
     exit
 fi
 if [[ "$knownHash" != "$recoveredHash" ]]; then
