blah

diff --git a/scripts/scache_store_stream b/scripts/scache_store_stream
--- a/scripts/scache_store_stream
+++ b/scripts/scache_store_stream
@@ -79,7 +79,7 @@ dbDir=/Ember\ Library/Futuramerlin\ Projects/Data/Stream\ Registry
         fi
         # Check that the data can be restored
         if [[ "$1" == "--verbose" ]]; then
-            scache_verify_entry 30 "$dbFilePath" || error-die "Failed saving stream: stored stream could not be read!"
+            scache_verify_entry 1000 "$dbFilePath" || error-die "Failed saving stream: stored stream could not be read!"
         else
             scache_verify_entry 5 "$dbFilePath" &> /dev/null || error-die "Failed saving stream: stored stream could not be read!"
         fi
