blah

diff --git a/scripts/scache_store_stream b/scripts/scache_store_stream
--- a/scripts/scache_store_stream
+++ b/scripts/scache_store_stream
@@ -76,7 +76,11 @@ dbDir=/Ember\ Library/Futuramerlin\ Projects/Data/Stream\ Registry
             find "$streamId.LocalStore" -type f -exec scachei_bundle_pointer "$pointerName" {} \;
         fi
         # Check that the data can be restored
-        scache_verify_entry 5 "$dbFilePath" &> /dev/null || error-die "Failed saving stream: stored stream could not be read!"
+        if [[ "$1" == "--verbose" ]]; then
+            scache_verify_entry 5 "$dbFilePath" &> /dev/null || error-die "Failed saving stream: stored stream could not be read!"
+        else
+            scache_verify_entry 5 "$dbFilePath" || error-die "Failed saving stream: stored stream could not be read!"
+        fi
     fi
     if [[ "$1" != "--verbose" ]]; then
         cat "$dbFilePath"
