Update Ember tree

diff --git a/scripts/sregi_hashpointer_sane b/scripts/sregi_hashpointer_sane
--- a/scripts/sregi_hashpointer_sane
+++ b/scripts/sregi_hashpointer_sane
@@ -6,15 +6,23 @@ source ember_bash_setup &> /dev/null
 ((EUID)) && exec sudo -- "$0" "$@"
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
-failCheckFile="$1"
-if [[ -e "$failCheckFile" ]]; then
-    die "A previous invocation of $0 failed with the message \"$(<"$failCheckFile")\"! Aborting."
-else
-    echo "$0 running in $(readlink -f "$(pwd)") with the arguments $@" > "$failCheckFile" || echo "$0 running in an unknown directory with the arguments $@" > "$failCheckFile"
+failCheckFile=""
+if [[ "$1" == "--fail-check" ]]; then
+    shift
+    failCheckFile="$1"
+    shift
 fi
-shift
+if [[ -n "$failCheckFile" ]]; then
+    if [[ -e "$failCheckFile" ]]; then
+        die "A previous invocation of $0 failed with the message \"$(<"$failCheckFile")\"! Aborting."
+    else
+        echo "$0 running in $(readlink -f "$(pwd)") with the arguments $@" > "$failCheckFile" || echo "$0 running in an unknown directory with the arguments $@" > "$failCheckFile"
+    fi
+fi
 success() {
-    rm -f "${failCheckFile:?}"
+    if [[ -n "$failCheckFile" ]]; then
+        rm -f "${failCheckFile:?}"
+    fi
     exit 0
 }
 
