Update Git repository using egup-single

diff --git a/scripts/sreg_build_reverse_index b/scripts/sreg_build_reverse_index
--- a/scripts/sreg_build_reverse_index
+++ b/scripts/sreg_build_reverse_index
@@ -25,7 +25,7 @@ enrollFile() {
     local link
     link="$dbDir/${hash:0:1}/${hash:1:1}/${hash:2:1}/$hash"
     if [[ ! -f "$link" ]]; then
-        [[ -e "$link" ]] && rm "$link" || die "Could not remove link $link"
+        [[ -e "$link" ]] && rm "$link" || die "Could not remove index record $link"
         print "$file" > "$link"
     fi
 }
