Update Ember tree

diff --git a/scripts/sregi_check_failed_entry b/scripts/sregi_check_failed_entry
--- a/scripts/sregi_check_failed_entry
+++ b/scripts/sregi_check_failed_entry
@@ -10,7 +10,7 @@ failCheckFile="$1"
 if [[ -e "$failCheckFile" ]]; then
     die "A previous invocation of $0 failed with the message \"$(<"$failCheckFile")\"! Aborting."
 else
-    echo "$0 running in $(readlink -f "$(pwd)") with the arguments $@" > "$failCheckFile" || echo "$0 running in an unknown directory with the arguments $@" > "$failCheckFile"
+    echo "$0 running in $(readlink -f "$(pwd)") with the arguments $*" > "$failCheckFile" || echo "$0 running in an unknown directory with the arguments $*" > "$failCheckFile"
 fi
 shift
 success() {
