Update Ember tree

diff --git a/scripts/sreg_read_stream b/scripts/sreg_read_stream
--- a/scripts/sreg_read_stream
+++ b/scripts/sreg_read_stream
@@ -55,7 +55,22 @@ mkdir "$streamId"
     numTotalRetries="$numRetries"
     successfulRetrieval="0"
     # Get the hash of the stream
-    hashFull="$(tail -c +38 "$streamId.xz" | head -c 129)"
+    function pipecheck() {
+        if [[ "${PIPESTATUS[0]}" != "141" ]] || [[ "${PIPESTATUS[0]}" != "0" ]]; then
+            # Ignore status 141, which just means the input stream was terminated by head before all the data were consumed
+            die "Failed reading temporary stream file"
+        fi
+        if [[ "${PIPESTATUS[1]}" != "0" ]]; then
+            die "Failed executing head on temporary stream file"
+        fi
+    }
+    set +o pipefail
+    hashFull="$(
+            tail -c +38 "$streamId.xz" | head -c 129
+            pipecheck
+        )"
+    set -o pipefail
+    unset -f pipecheck
     if [[ -n "$knownChecksum" ]]; then
         [[ "$knownChecksum" == "$hashFull" ]] || die "The checksum provided by the pointer does not match the provided checksum."
     fi
