Update Ember tree

diff --git a/scripts/sreg_flush_localstore b/scripts/sreg_flush_localstore
--- a/scripts/sreg_flush_localstore
+++ b/scripts/sreg_flush_localstore
@@ -5,6 +5,14 @@ source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
 
+sregDir=""
+if [[ "$1" == "--sreg-dir" ]]; then
+    shift
+    sregDir="$1"
+    shift
+fi
+sregDir="$(sregi_find_dir --sreg-dir "$sregDir" --full-check)"
+
 finish() {
     if cd "$crystalWorkdir"; then
         if [[ -e "${streamId:?}" ]]; then
@@ -14,7 +22,7 @@ finish() {
 }
 trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; rm -f "$dbDir"/.LocalStore.lock; finish; exit 1' ERR
 
-dbDir="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Stream\ Registry
+dbDir="$sregDir"
 crystalWorkdir="$(crystallize-getconf WorkDirectory)"
 streamId="sreg_flush_localstore-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
 mkdir -p "$crystalWorkdir/$streamId"
@@ -38,7 +46,7 @@ mkdir -p "$crystalWorkdir/$streamId"
         pointerName="$(readlink -f "$streamId.bundle.pointer")"
         mkdir -p "$dbDir/Packs/"
         rsync -q --checksum "$pointerName" "$dbDir/Packs/"
-        find "$streamId.LocalStore" -type f -exec sregi_bundle_pointer "$pointerName" {} "$crystalWorkdir" \; || die "Failed running sreg_flush_localstore!"
+        find "$streamId.LocalStore" -type f -exec sregi_bundle_pointer --sreg-dir "$sregDir" "$pointerName" {} "$crystalWorkdir" \; || die "Failed running sreg_flush_localstore!"
         rm -r "$dbDir"/LocalStore
         rm "$dbDir"/.LocalStore.lock
         mkdir -p "$dbDir"/LocalStore
