Update Ember tree

diff --git a/scripts/sreg_store_stream b/scripts/sreg_store_stream
--- a/scripts/sreg_store_stream
+++ b/scripts/sreg_store_stream
@@ -151,9 +151,9 @@ mkdir -p "$crystalWorkdir/.$streamId/$streamId"
         pointerTypeSignature="c39f8657-384b-438b-a5a2-eece17147589"
         if [[ "$useLocalStore" != "true" ]]; then
             if [[ "$1" == "--verbose" ]]; then
-                crystallize --passphrase "$(sregi_get_passphrase "$sregDir")" --leave-pointer "$streamId.tmp" | 1&>2
+                crystallize --leave-locked --passphrase "$(sregi_get_passphrase "$sregDir")" --leave-pointer "$streamId.tmp" | 1&>2
             else
-                crystallize --passphrase "$(sregi_get_passphrase "$sregDir")" --leave-pointer "$streamId.tmp" &> /dev/null
+                crystallize --leave-locked --passphrase "$(sregi_get_passphrase "$sregDir")" --leave-pointer "$streamId.tmp" &> /dev/null
             fi
             pointerTypeSignature="a5e2f296-3085-49c0-8f48-24ea436b7a8b"
         fi
@@ -168,7 +168,7 @@ mkdir -p "$crystalWorkdir/.$streamId/$streamId"
             checkedxz --quiet "$streamId.tmp" --stdout -k -C sha256 -T 0 -9 -e > "$localStoreFilePath"
         fi
         trap finish EXIT
-        sregi_verify_entry --sreg-dir "$sregDir" "$tmpFilePath" > /dev/null || die "Failed saving stream: stored stream could not be read!"
+        sregi_verify_entry --lock-override --sreg-dir "$sregDir" "$tmpFilePath" > /dev/null || die "Failed saving stream: stored stream could not be read!"
         trap - EXIT
         mv "$tmpFilePath" "$dbFilePath" || die "Could not move pointer into place!"
     fi
