Update Ember tree

diff --git a/scripts/sreg_read_stream b/scripts/sreg_read_stream
--- a/scripts/sreg_read_stream
+++ b/scripts/sreg_read_stream
@@ -39,7 +39,7 @@ dbDir="${EmberLibrary:?}/Futuramerlin Projects/Data/Stream Registry/"
 # Basic sanity check to make sure it bombs out if the pointer is cached but is missing a necessary LocalStore entry
 if [[ -z "$overrideEntryPath" ]]; then
     if [[ -n "$knownChecksum" ]]; then
-        sregi_available_by_hash
+        sregi_available_by_hash || die "sregi_available_by_hash failed on ${BASH_SOURCE[0]} line ${LINENO} while reading $knownChecksum."
     fi
 fi
 # Set up cache directory
