blah

diff --git a/scripts/sregi_replace_conditional b/scripts/sregi_replace_conditional
--- a/scripts/sregi_replace_conditional
+++ b/scripts/sregi_replace_conditional
@@ -11,6 +11,14 @@ if ! [ -f "$1" ]; then
     exit 1
 fi
 if [[ "$(head -c 36 "$1")" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
-    exit 0
+    if [[ sreg_verify_entry "$1" ]]; then
+        exit 0
+    else
+        warn "Entry $1 failed verification! Entry contents: "
+        cat "$1"
+        echo "Removing pointer; it should be re-created on the next sync."
+        rm "$1"
+        exit 1
+    fi
 fi
 sreg_store_files --replace "$1"
