Update Ember tree

diff --git a/scripts/sregi_drop_single_unused b/scripts/sregi_drop_single_unused
--- a/scripts/sregi_drop_single_unused
+++ b/scripts/sregi_drop_single_unused
@@ -13,7 +13,7 @@ failCheckFile="$1"
 if [[ -e "$failCheckFile" ]]; then
     warn "A previous invocation of $0 failed with the message \"$(<"$failCheckFile")\"!"
 else
-    echo "$0 running in $(readlink -f "$(pwd)") with the arguments $*" > "$failCheckFile" || echo "$0 running in an unknown directory with the arguments $*" > "$failCheckFile"
+    echo "$0 running at $(emdate) in $(readlink -f "$(pwd)") with the arguments $*" > "$failCheckFile" || echo "$0 running at $(emdate) in an unknown directory with the arguments $*" > "$failCheckFile"
     success() {
         rm -f "${failCheckFile:?}"
         exit 0
