Update Ember tree

diff --git a/scripts/sreg_flush_localstore b/scripts/sreg_flush_localstore
--- a/scripts/sreg_flush_localstore
+++ b/scripts/sreg_flush_localstore
@@ -56,6 +56,9 @@ statusFile="/tmp/$streamId.sreg_flush_localstore.status"
         else
             crystallize --passphrase "$(sregi_get_passphrase "$sregDir")" --leave-pointer "$streamId.LocalStore" &> /dev/null
         fi
+        if [[ ! -e "$streamId.LocalStore.crystal" ]] || [[ ! -e ".$streamId.LocalStore.crystal-data" ]]; then
+            die "Crystal data does not seem to exist! Did crystallizing fail, and not trigger the error trap for some reason?" # I think this is the condition that causes the "Pointer pax was corrupt" problem. If that happens after adding this check, something else weird is going on.
+        fi
         # (2fa... is the remote bundle pointer type signature)
         mv "$streamId.LocalStore.tmp" "$streamId.LocalStore"
         tar -c -P -S --format pax "$streamId.LocalStore.crystal" ".$streamId.LocalStore.crystal-data" > "$streamId.bundle.pointer.tar"
