Update Git repository using egup-single

diff --git a/scripts/sregi_copy_write b/scripts/sregi_copy_write
--- a/scripts/sregi_copy_write
+++ b/scripts/sregi_copy_write
@@ -84,123 +84,124 @@ if [[ "$1" == "--no-verify" ]]; then
     shift
 fi
 #echo "$@"
-if ! [[ -f "$1" ]]; then
-    error-notify "Item must be a regular file."
-    exit 1
-fi
-fsckStatusFile="$3"
-if [[ -n "$fsckStatusFile" ]]; then
-    numberExpected="$(<"$fsckStatusFile")"
-    numberProcessedFile="$fsckStatusFile.done"
-    if ! [[ -f "$numberProcessedFile" ]]; then
-        numberProcessed="1"
+if [[ -f "$1" ]]; then
+    fsckStatusFile="$3"
+    if [[ -n "$fsckStatusFile" ]]; then
+        numberExpected="$(<"$fsckStatusFile")"
+        numberProcessedFile="$fsckStatusFile.done"
+        if ! [[ -f "$numberProcessedFile" ]]; then
+            numberProcessed="1"
+        else
+            numberProcessed="$(<"$numberProcessedFile")"
+            numberProcessed=$(( numberProcessed + 1 ))
+        fi
+        echo "$numberProcessed" > "$numberProcessedFile"
+        if [[ "$numberExpected" == "0" ]]; then
+            # wtf?
+            numberExpected="-1"
+        fi
+        numberProcessedPercentage="$(printf "%.3f\\n" "$(bc -l <<< "($numberProcessed / $numberExpected) * 100")")"
+        echo "Copying item $1: #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
     else
-        numberProcessed="$(<"$numberProcessedFile")"
-        numberProcessed=$(( numberProcessed + 1 ))
+        echo "Copying item $1."
     fi
-    echo "$numberProcessed" > "$numberProcessedFile"
-    if [[ "$numberExpected" == "0" ]]; then
-        # wtf?
-        numberExpected="-1"
-    fi
-    numberProcessedPercentage="$(printf "%.3f\\n" "$(bc -l <<< "($numberProcessed / $numberExpected) * 100")")"
-    echo "Copying item $1: #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
-else
-    echo "Copying item $1."
-fi
-# FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
-# shellcheck disable=SC2034
-destinationRootLength="$4"
-# FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
-# shellcheck disable=SC2034
-sourceNameReplaced="${1/%.git/.git.686fc528-0e8e-4724-91bb-c103cdcdd592}"
-sourceNameReplaced="${sourceNameReplaced//\/.git\//\/.git.686fc528-0e8e-4724-91bb-c103cdcdd592\/}"
-sourceNameReplaced="${sourceNameReplaced/%.gitignore/.gitignore.24355e64-bfd5-4cb7-92f9-4417fb55ccfd}"
-sourceNameReplaced="${sourceNameReplaced//\/.gitignore\//\/.gitignore.24355e64-bfd5-4cb7-92f9-4417fb55ccfd\/}"
-sourceNameReplaced="${sourceNameReplaced/%.gitmodules/.gitmodules.e17e15dc-7ed4-4b99-8acb-019f503afb9e}"
-sourceNameReplaced="${sourceNameReplaced//\/.gitmodules\//\/.gitmodules.e17e15dc-7ed4-4b99-8acb-019f503afb9e\/}"
-targetLength=${#sourceNameReplaced}
-#echo "$destinationRootLength - $targetLength"
-destinationName="$2/${sourceNameReplaced:destinationRootLength:targetLength}"
-#echo "$destinationName"
-sourceChecksum="$(sha512sum < "$1" | awk '{print $1;}')"
-if [[ -f "$destinationName" ]]; then
-    pointerTypeSignature="$(head -c 36 "$destinationName" | tr -d '\0')"
-    destinationChecksum=""
-    hasEncounteredError="0"
-    if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
-        trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; hasEncounteredError="1"' ERR
-        assumePointerDbEntryFileExists="true"
-        if [[ "$sregNoVerify" == "true" ]]; then
-            destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
-            pointerDbEntryFile="$sregDir/${destinationChecksum:0:1}/${destinationChecksum:1:1}/${destinationChecksum:2:1}/$destinationChecksum"
-            if ! [[ -e "$pointerDbEntryFile" ]]; then
-                assumePointerDbEntryFileExists="pointerDbEntryFile $pointerDbEntryFile missing!"
-            else
-                innerPointerTypeSignature="$(head -c 36 "$pointerDbEntryFile")"
-                if [[ "$innerPointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]]; then
-                    localStoreToTest="$sregDir/LocalStore/${destinationChecksum:0:1}/${destinationChecksum:1:1}/${destinationChecksum:2:1}/$destinationChecksum"
-                    if ! [[ -e "$localStoreToTest" ]]; then
-                        assumePointerDbEntryFileExists="LocalStore $localStoreToTest missing!"
+    # FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
+    # shellcheck disable=SC2034
+    destinationRootLength="$4"
+    # FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
+    # shellcheck disable=SC2034
+    sourceNameReplaced="${1/%.git/.git.686fc528-0e8e-4724-91bb-c103cdcdd592}"
+    sourceNameReplaced="${sourceNameReplaced//\/.git\//\/.git.686fc528-0e8e-4724-91bb-c103cdcdd592\/}"
+    sourceNameReplaced="${sourceNameReplaced/%.gitignore/.gitignore.24355e64-bfd5-4cb7-92f9-4417fb55ccfd}"
+    sourceNameReplaced="${sourceNameReplaced//\/.gitignore\//\/.gitignore.24355e64-bfd5-4cb7-92f9-4417fb55ccfd\/}"
+    sourceNameReplaced="${sourceNameReplaced/%.gitmodules/.gitmodules.e17e15dc-7ed4-4b99-8acb-019f503afb9e}"
+    sourceNameReplaced="${sourceNameReplaced//\/.gitmodules\//\/.gitmodules.e17e15dc-7ed4-4b99-8acb-019f503afb9e\/}"
+    targetLength=${#sourceNameReplaced}
+    #echo "$destinationRootLength - $targetLength"
+    destinationName="$2/${sourceNameReplaced:destinationRootLength:targetLength}"
+    #echo "$destinationName"
+    sourceChecksum="$(sha512sum < "$1" | awk '{print $1;}')"
+    if [[ -f "$destinationName" ]]; then
+        pointerTypeSignature="$(head -c 36 "$destinationName" | tr -d '\0')"
+        destinationChecksum=""
+        hasEncounteredError="0"
+        if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
+            trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; hasEncounteredError="1"' ERR
+            assumePointerDbEntryFileExists="true"
+            if [[ "$sregNoVerify" == "true" ]]; then
+                destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
+                pointerDbEntryFile="$sregDir/${destinationChecksum:0:1}/${destinationChecksum:1:1}/${destinationChecksum:2:1}/$destinationChecksum"
+                if ! [[ -e "$pointerDbEntryFile" ]]; then
+                    assumePointerDbEntryFileExists="pointerDbEntryFile $pointerDbEntryFile missing!"
+                else
+                    innerPointerTypeSignature="$(head -c 36 "$pointerDbEntryFile")"
+                    if [[ "$innerPointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]]; then
+                        localStoreToTest="$sregDir/LocalStore/${destinationChecksum:0:1}/${destinationChecksum:1:1}/${destinationChecksum:2:1}/$destinationChecksum"
+                        if ! [[ -e "$localStoreToTest" ]]; then
+                            assumePointerDbEntryFileExists="LocalStore $localStoreToTest missing!"
+                        fi
                     fi
                 fi
+            else
+                destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129 | tr -d '\0')"
+                sreg_read_stream --sreg-dir "$sregDir" < "$destinationName" > /dev/null || hasEncounteredError="1"
+            fi
+            if [[ "$destinationChecksum" == "$sourceChecksum" && "$hasEncounteredError" == "0" && "$assumePointerDbEntryFileExists" == "true" ]]; then
+                # The file is already present, pointerized, and readable, so exit without doing anything.
+                echo "(Nothing done for $1.)"
+                success
+            else
+                warn "(Note: Destination pointer $destinationName did not match source checksum or could not be read (source checksum: $sourceChecksum / destinationChecksum: $destinationChecksum /  stream read status: $hasEncounteredError / quick check status: $assumePointerDbEntryFileExists / destination pointer contents: $(<"$destinationName")): the source file has probably been changed. Removing and recreating.)"
+                # cat "$destinationName"
+                rm "${destinationName:?}"
             fi
         else
-            destinationChecksum="$(tail -c +38 "$destinationName" | head -c 129 | tr -d '\0')"
-            sreg_read_stream --sreg-dir "$sregDir" < "$destinationName" > /dev/null || hasEncounteredError="1"
-        fi
-        if [[ "$destinationChecksum" == "$sourceChecksum" && "$hasEncounteredError" == "0" && "$assumePointerDbEntryFileExists" == "true" ]]; then
-            # The file is already present, pointerized, and readable, so exit without doing anything.
-            echo "(Nothing done for $1.)"
-            success
-        else
-            warn "(Note: Destination pointer $destinationName did not match source checksum or could not be read (source checksum: $sourceChecksum / destinationChecksum: $destinationChecksum /  stream read status: $hasEncounteredError / quick check status: $assumePointerDbEntryFileExists / destination pointer contents: $(<"$destinationName")): the source file has probably been changed. Removing and recreating.)"
-            # cat "$destinationName"
-            rm "${destinationName:?}"
-        fi
-    else
-        if [[ "$pointerTypeSignature" != "760fa662-89cf-4ebd-9664-150b7637ddd4" ]] && # Hash pointer
-            [[ "$pointerTypeSignature" != "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] && # Standard remote pointer
-            [[ "$pointerTypeSignature" != "c39f8657-384b-438b-a5a2-eece17147589" ]] && # LocalStore pointer
-            [[ "$pointerTypeSignature" != "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] && # Remote pack pointer
-            [[ "$pointerTypeSignature" != "2fae2004-94bb-4aa8-a01a-fc44298efc2c" ]] && # Also remote pack pointer
-            [[ "$pointerTypeSignature" != "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] && # Pack pointer data is in the pointer
-            [[ "$pointerTypeSignature" != "45baff46-8db7-46f6-aad9-de5f713b02fe" ]] # URL pointer
-        then
-            if [[ "$sourceChecksum" == "$(sha512sum < "$destinationName" | awk '{print $1;}')" ]]; then
-                echo "(Skipping matching normal file $destinationName)"
-                success
+            if [[ "$pointerTypeSignature" != "760fa662-89cf-4ebd-9664-150b7637ddd4" ]] && # Hash pointer
+                [[ "$pointerTypeSignature" != "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] && # Standard remote pointer
+                [[ "$pointerTypeSignature" != "c39f8657-384b-438b-a5a2-eece17147589" ]] && # LocalStore pointer
+                [[ "$pointerTypeSignature" != "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] && # Remote pack pointer
+                [[ "$pointerTypeSignature" != "2fae2004-94bb-4aa8-a01a-fc44298efc2c" ]] && # Also remote pack pointer
+                [[ "$pointerTypeSignature" != "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] && # Pack pointer data is in the pointer
+                [[ "$pointerTypeSignature" != "45baff46-8db7-46f6-aad9-de5f713b02fe" ]] # URL pointer
+            then
+                if [[ "$sourceChecksum" == "$(sha512sum < "$destinationName" | awk '{print $1;}')" ]]; then
+                    echo "(Skipping matching normal file $destinationName)"
+                    success
+                fi
             fi
         fi
     fi
-fi
-trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
-crystalWorkdir="$(crystallize-getconf WorkDirectory)"
-streamId=".sreg-$(date-uuid)"
-crystalSubdir="$crystalWorkdir/$streamId"
-mkdir -p "$crystalSubdir"
-rsync -a --checksum --no-i-r "$1" "$crystalSubdir/"
-setVariableToCommandOutput "basename" "embasename" "$1"
-fileToStash="$crystalSubdir/${basename:?}"
-if [[ -f "$fileToStash" ]]; then
-    sreg_store_stream --sreg-dir "$sregDir" --assume-checksum "$sourceChecksum" --verbose < "$fileToStash" | bigSponge "$fileToStash"
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
+    crystalWorkdir="$(crystallize-getconf WorkDirectory)"
+    streamId=".sreg-$(date-uuid)"
+    crystalSubdir="$crystalWorkdir/$streamId"
+    mkdir -p "$crystalSubdir"
+    rsync -a --checksum --no-i-r "$1" "$crystalSubdir/"
+    setVariableToCommandOutput "basename" "embasename" "$1"
+    fileToStash="$crystalSubdir/${basename:?}"
+    if [[ -f "$fileToStash" ]]; then
+        sreg_store_stream --sreg-dir "$sregDir" --assume-checksum "$sourceChecksum" --verbose < "$fileToStash" | bigSponge "$fileToStash"
+    else
+        die "Skipping item $fileToStash: not a regular file."
+    fi
+    mkdir -p "$(dirname "$destinationName")"
+    rsync -a --checksum --no-i-r "$fileToStash" "$destinationName"
+    # a+r gives (a)ll users (r)ead permission
+    chmod a+r "$destinationName"
+
+    # Checksum the source once again, and compare it to the stored pointer, just to make sure.
+    pointerChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
+    if [[ "$pointerChecksum" != "$(sha512sum < "$1" | awk '{print $1;}')" ]] || [[ "$pointerChecksum" != "$sourceChecksum" ]]; then
+        die
+    fi
+
+    rm -r "${crystalSubdir:?}"
+    if [[ -e "${streamId:?}" ]]; then
+        rm -r "${streamId:?}"
+    fi
 else
-    die "Skipping item $fileToStash: not a regular file."
-fi
-mkdir -p "$(dirname "$destinationName")"
-rsync -a --checksum --no-i-r "$fileToStash" "$destinationName"
-# a+r gives (a)ll users (r)ead permission
-chmod a+r "$destinationName"
-
-# Checksum the source once again, and compare it to the stored pointer, just to make sure.
-pointerChecksum="$(tail -c +38 "$destinationName" | head -c 129)"
-if [[ "$pointerChecksum" != "$(sha512sum < "$1" | awk '{print $1;}')" ]] || [[ "$pointerChecksum" != "$sourceChecksum" ]]; then
-    die
-fi
-
-rm -r "${crystalSubdir:?}"
-if [[ -e "${streamId:?}" ]]; then
-    rm -r "${streamId:?}"
+    error-notify "Item must be a regular file."
+    exit 1
 fi
 
 finish
