Update Ember tree

diff --git a/scripts/sregi_expand_pointers b/scripts/sregi_expand_pointers
--- a/scripts/sregi_expand_pointers
+++ b/scripts/sregi_expand_pointers
@@ -28,7 +28,7 @@ if [[ -n "$failCheckFile" ]]; then
     if [[ -e "$failCheckFile" ]]; then
         warn "A previous invocation of $0 failed with the message \"$(<"$failCheckFile")\"!"
     else
-        echo "$0 running at $(emdate) in $(readlink -f "$(pwd)") with the arguments $*" > "$failCheckFile" || echo "$0 running at $(emdate) in an unknown directory with the arguments $*" > "$failCheckFile"
+        echo "$0 running at $(emdate) in $(readlink -f "$(pwd)") with the remaining arguments $*" > "$failCheckFile" || echo "$0 running at $(emdate) in an unknown directory with the remaining arguments $*" > "$failCheckFile"
         success() {
             if [[ -n "$failCheckFile" ]]; then
                 rm -f "${failCheckFile:?}"
