Update Git repository using egup-single

diff --git a/scripts/sreg_build_reverse_index b/scripts/sreg_build_reverse_index
--- a/scripts/sreg_build_reverse_index
+++ b/scripts/sreg_build_reverse_index
@@ -45,6 +45,7 @@ fi
 mkdir -p "$dbDir"
 
 count="0"
+error="false"
 enrollFile() {
     local dbDir
     dbDir="$2"
@@ -64,7 +65,8 @@ enrollFile() {
     fi
     if [[ ! -f "$link" ]]; then
         if [[ -e "$link" ]]; then
-            rm "$link" || warn "Could not remove index record $link"
+            if ! rm "$link"; then
+                warn "Could not remove index record $link"
         else
             # Should not be necessary if there was already a file there
             mkdir -p "$(dirname "$link")"
