Update Ember tree

diff --git a/scripts/sregi_expand_pointers b/scripts/sregi_expand_pointers
--- a/scripts/sregi_expand_pointers
+++ b/scripts/sregi_expand_pointers
@@ -5,6 +5,26 @@ source ember_bash_setup &> /dev/null
 ((EUID)) && exec sudo -- "$0" "$@"
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
+fsckStatusFile="$1"
+shift
+
+if [[ -n "$fsckStatusFile" ]]; then
+    numberExpected="$(<"$fsckStatusFile")"
+    numberProcessedFile="$fsckStatusFile.done"
+    if ! [[ -f "$numberProcessedFile" ]]; then
+        numberProcessed="1"
+    else
+        numberProcessed="$(<"$numberProcessedFile")"
+        numberProcessed=$(( numberProcessed + 1 ))
+    fi
+    echo "$numberProcessed" > "$numberProcessedFile"
+    if [[ "$numberExpected" == "0" ]]; then
+        numberExpected="-1"
+    fi
+    numberProcessedPercentage="$(printf "%.3f\n" "$(bc -l <<< "($numberProcessed / $numberExpected) * 100")")"
+    echo "Resolving item $pointerId: #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
+fi
+
 while [[ ! -z "$1" ]]; do
     echo "Items remaining to resolve: "
     echo "$@"
@@ -13,7 +33,7 @@ while [[ ! -z "$1" ]]; do
     if [[ -f "$fileToResolve" ]]; then
         # FIXME: This shellcheck directive is only needed for outdated shellcheck versions. Once CodeClimate's shellcheck gets updated (which probably means when Debian stable updates shellcheck), it can be removed.
         # shellcheck disable=SC2094
-        sreg_read_stream < "$fileToResolve" | sponge "$fileToResolve" || echo "(Note: ignoring failed read of $fileToResolve)"
+        sreg_read_stream < "$fileToResolve" | sponge "$fileToResolve" || die "Reading $fileToResolve failed."
     else
         if [[ -d "$fileToResolve" ]]; then
             find "$fileToResolve" -type f -exec sregi_expand_pointers {} \;
@@ -21,8 +41,5 @@ while [[ ! -z "$1" ]]; do
             warn "Skipping item $fileToResolve: not a regular file or directory."
         fi
     fi
-    echo "Done resolving $fileToResolve." || warn "Failed resolving $fileToResolve!"
     shift
 done
-#printf "\033c"
-echo "Done resolving all items."
diff --git a/scripts/srpull b/scripts/srpull
--- a/scripts/srpull
+++ b/scripts/srpull
@@ -3,14 +3,39 @@
 source ember_bash_setup &> /dev/null
 
 ((EUID)) && exec sudo -- "$0" "$@"
-trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
+#set -x
 
-rsync -av --checksum --progress --no-i-r --ignore-existing "$1" "$2/"
-rsync -av --checksum --progress --no-i-r --ignore-existing "$1" "$2/"
+function finish() {
+    if [[ -e "${streamId:?}" ]]; then
+        rm -r "${streamId:?}" "/tmp/${fsckId:?}.status"
+    fi
+}
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; finish; exit 1' ERR
+
+srpullReplace="false"
+if [[ "$1" == "--replace" ]]; then
+    srpullReplace="true"
+    shift
+fi
+
+if [[ "$srpullReplace" == "true" ]]; then
+    rsync -av --checksum --progress --no-i-r "$1" "$2/"
+    rsync -av --checksum --progress --no-i-r "$1" "$2/"
+else
+    rsync -av --checksum --progress --no-i-r --ignore-existing "$1" "$2/"
+    rsync -av --checksum --progress --no-i-r --ignore-existing "$1" "$2/"
+fi
 
 destinationFindTarget="$2/$(basename "$1")/"
 if [[ "$1" =~ '/'$ ]]; then
     destinationFindTarget="$2/"
 fi
 
-sregi_expand_pointers "$destinationFindTarget"
+fsckId="srpull-$(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")"
+fsckStatusFile="/tmp/$fsckId.status"
+
+find "$destinationFindTarget" -printf '.' | wc -c > "$fsckStatusFile"
+
+sregi_expand_pointers "$fsckStatusFile" "$destinationFindTarget"
+
+finish
