Update Ember tree

diff --git a/scripts/sregi_check_failed_entry b/scripts/sregi_check_failed_entry
--- a/scripts/sregi_check_failed_entry
+++ b/scripts/sregi_check_failed_entry
@@ -8,7 +8,7 @@ trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
 fsckStatusFile="$2"
 knownHash="(Failed to retrieve entry hash!)"
-knownHashTemp="$(sregi_hash_from_file "$1")" || die "$1"
+knownHashTemp="$(sregi_hash_from_file "$1")" || exit 1
 if [[ -n "$knownHashTemp" ]]; then
     knownHash="$knownHashTemp"
 fi
@@ -39,11 +39,11 @@ if sreg_read_stream --entry-path "$1" --checksum "$knownHash" --disallow-hash-po
             numberExpected="-1"
         fi
         numberProcessedPercentage="$(printf "%.3f\n" "$(bc -l <<< "($numberProcessed / $numberExpected) * 100")")"
-        echo "Verified stream registry database entry $knownHash: finished #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
+        echo "Verified and restored to stream registry database formerly failed entry $knownHash: finished #$numberProcessed of $numberExpected ($numberProcessedPercentage%)"
     else
-        echo "Verified stream registry database entry $knownHash."
+        echo "Verified and restored to stream registry database formerly failed entry $knownHash."
     fi
-    exit
+    exit 0
 else
-    die
+    exit 1
 fi
