Update Ember tree

diff --git a/scripts/sreg_store_stream b/scripts/sreg_store_stream
--- a/scripts/sreg_store_stream
+++ b/scripts/sreg_store_stream
@@ -98,13 +98,13 @@ dbDir="${EmberLibrary:?}"/Futuramerlin\ Projects/Data/Stream\ Registry
             find "$streamId.LocalStore" -type f -exec sregi_bundle_pointer "$pointerName" {} \;
         fi
         # Check that the data can be restored
-        if [[ "$1" == "--verbose" ]]; then
-            sregi_verify_entry "$dbFilePath" || die "Failed saving stream: stored stream could not be read!"
-        else
+        #if [[ "$1" == "--verbose" ]]; then
+            #sregi_verify_entry "$dbFilePath" || die "Failed saving stream: stored stream could not be read!"
+        #else
             trap finish EXIT
             sregi_verify_entry "$dbFilePath" &> /dev/null || die "Failed saving stream: stored stream could not be read!"
             trap - EXIT
-        fi
+        #fi
     fi
     if [[ "$1" != "--verbose" ]]; then
         cat "$dbFilePath"
