Update Ember tree

diff --git a/scripts/sreg_store_stream b/scripts/sreg_store_stream
--- a/scripts/sreg_store_stream
+++ b/scripts/sreg_store_stream
@@ -117,7 +117,7 @@ mkdir -p "$crystalWorkdir/$streamId"
             xz -k -C sha256 -T 0 --lzma2=preset=1 --stdout "$streamId.tmp" > "$localStoreFilePath"
         fi
         trap finish EXIT
-        sregi_verify_entry "$tmpFilePath" &> /dev/null || die "Failed saving stream: stored stream could not be read!"
+        sregi_verify_entry --sreg-dir "$sregDir" "$tmpFilePath" &> /dev/null || die "Failed saving stream: stored stream could not be read!"
         trap - EXIT
         mv "$tmpFilePath" "$dbFilePath" || die "Could not move pointer into place!"
     fi
