version

diff --git a/scripts/sreg_read_stream b/scripts/sreg_read_stream
--- a/scripts/sreg_read_stream
+++ b/scripts/sreg_read_stream
@@ -89,6 +89,9 @@ mkdir "$streamId"
                 crystalFilePattern=".*.crystal-data"
                 crystalFilePatternMatches=( $crystalFilePattern )
                 localStoreCrystalName="${crystalFilePatternMatches[0]}"
+                if ! [ -e "$localStoreCrystalName" ]; then
+                    error-die "Crystal info could not be found in the pointer, so giving up immediately (retrying probably wouldn't help this)."
+                fi
                 localStoreCrystalIdentifier="$(<"$localStoreCrystalName"/identifier)"
                 localstoreLocation="$(localstorecache_request "$crystalWorkdir/.LocalStoreCache/" "$localStoreCrystalIdentifier")"
                 unxz --stdout - < "$localstoreLocation/scache-"*".LocalStore/$hashA/$hashB/$hashC/$hashFull" > "$streamId.out"
diff --git a/scripts/sreg_store_stream b/scripts/sreg_store_stream
--- a/scripts/sreg_store_stream
+++ b/scripts/sreg_store_stream
@@ -4,10 +4,12 @@ source "$(which ember_bash_setup)" &> /dev/null
 # Stores data provided on stdin into the stream registry, and sends a pointer to it to stdout.
 
 [ "$(whoami)" != "root" ] && exec sudo -- "$0" "$@"
-trap 'error-die "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."' ERR
-# if [[ "$1" == "--verbose" ]]; then
-#     set -x
-# fi
+function finish() {
+    if [ -e "$streamId" ]; then
+        rm -r "$streamId"
+    fi
+}
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE} line ${LINENO}."; finish; exit 1' ERR
 
 crystalWorkdir="$(crystallize-getconf 'WorkDirectory')"
 dbDir="$EmberLibrary"/Futuramerlin\ Projects/Data/Stream\ Registry
