Update Git repository using egup-single

diff --git a/scripts/sreg_build_reverse_index b/scripts/sreg_build_reverse_index
--- a/scripts/sreg_build_reverse_index
+++ b/scripts/sreg_build_reverse_index
@@ -64,7 +64,7 @@ enrollFile() {
     fi
     if [[ ! -f "$link" ]]; then
         if [[ -e "$link" ]]; then
-            rm "$link" || die "Could not remove index record $link"
+            rm "$link" || warn "Could not remove index record $link"
         else
             # Should not be necessary if there was already a file there
             mkdir -p "$(dirname "$link")"
