Update Ember tree

diff --git a/scripts/sreg_store_stream b/scripts/sreg_store_stream
--- a/scripts/sreg_store_stream
+++ b/scripts/sreg_store_stream
@@ -46,11 +46,23 @@ mkdir -p "$crystalWorkdir/$streamId"
     else
         hashFull="$(sha512sum < "$streamId.tmp" | awk '{print $1;}')"
     fi
+    inputPointerTypeSignature=""
+    if ! [[ "$(wc -c < "$streamId.tmp")" -lt 166 ]]; then
+        inputPointerTypeSignature="$(head -c 36 "$streamId.tmp")"
+    fi
+    if [[ "$inputPointerTypeSignature" == "a5e2f296-3085-49c0-8f48-24ea436b7a8b" ]] || # Standard remote pointer
+        [[ "$inputPointerTypeSignature" == "c39f8657-384b-438b-a5a2-eece17147589" ]] || # LocalStore pointer
+        [[ "$inputPointerTypeSignature" == "2fae2004-94bb-4aa8-a01a-fc44298efc2c" ]] || # Remote pack pointer
+        [[ "$inputPointerTypeSignature" == "209fcfdf-d1ad-4345-8ef7-1fdc2d583d49" ]] || # Remote pack pointer, with pointer data in the pointer
+        [[ "$inputPointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]] # Hash pointer
+    then
+        die "The input stream is a sreg pointer, and cannot be safely stored."
+    fi
     if [[ -n "$outFile" ]]; then
         if [[ -f "$outFile" ]]; then
             pointerTypeSignature=""
-            if ! [[ "$(wc -c < "$streamId.tmp")" -lt 166 ]]; then
-                pointerTypeSignature="$(head -c 36 "$streamId.xz")"
+            if ! [[ "$(wc -c < "$outFile")" -lt 166 ]]; then
+                pointerTypeSignature="$(head -c 36 "$outFile")"
             fi
             if [[ "$pointerTypeSignature" == "760fa662-89cf-4ebd-9664-150b7637ddd4" ]]; then
                 # The file is a hash pointer. This is fine: continue nomally.
