Update Ember tree

diff --git a/scripts/sregi_check_failed_entry b/scripts/sregi_check_failed_entry
--- a/scripts/sregi_check_failed_entry
+++ b/scripts/sregi_check_failed_entry
@@ -6,6 +6,18 @@ source ember_bash_setup &> /dev/null
 ((EUID)) && exec sudo -- "$0" "$@"
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
+failCheckFile="$1"
+if [[ -e "$failCheckFile" ]]; then
+    die "A previous invocation of $0 failed with the message \"$(<"$failCheckFile")\"! Aborting."
+else
+    echo "$0 running in $(readlink -f "$(pwd)") with the arguments $@" > "$failCheckFile" || echo "$0 running in an unknown directory with the arguments $@" > "$failCheckFile"
+fi
+shift
+success() {
+    rm -f "${failCheckFile:?}"
+    exit 0
+}
+
 sregDir=""
 if [[ "$1" == "--sreg-dir" ]]; then
     shift
