version

diff --git a/scripts/sreg_store_stream b/scripts/sreg_store_stream
--- a/scripts/sreg_store_stream
+++ b/scripts/sreg_store_stream
@@ -85,7 +85,7 @@ dbDir="$EmberLibrary"/Futuramerlin\ Projects/Data/Stream\ Registry
         fi
         # Check that the data can be restored
         if [[ "$1" == "--verbose" ]]; then
-            sreg_verify_entry 100 "$dbFilePath" || error-die "Failed saving stream: stored stream could not be read!"
+            sreg_verify_entry 1 "$dbFilePath" || error-die "Failed saving stream: stored stream could not be read!"
         else
             sreg_verify_entry 5 "$dbFilePath" &> /dev/null || error-die "Failed saving stream: stored stream could not be read!"
         fi
