Update Git repository using egup-single

diff --git a/scripts/sreg_build_reverse_index b/scripts/sreg_build_reverse_index
--- a/scripts/sreg_build_reverse_index
+++ b/scripts/sreg_build_reverse_index
@@ -46,7 +46,9 @@ enrollFile() {
     local link
     link="$dbDir/${hash:0:1}/${hash:1:1}/${hash:2:1}/$hash"
     if [[ ! -f "$link" ]]; then
-        [[ -e "$link" ]] && rm "$link" || die "Could not remove index record $link"
+        if [[ -e "$link" ]]; then
+            rm "$link" || die "Could not remove index record $link"
+        fi
         print "$file" > "$link"
     fi
 }
