Update Ember tree

diff --git a/scripts/srsync b/scripts/srsync
--- a/scripts/srsync
+++ b/scripts/srsync
@@ -6,6 +6,19 @@ source ember_bash_setup &> /dev/null
 ((EUID)) && exec sudo -- "$0" "$@"
 trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
 
+finish() {
+    trap - ERR
+    if [[ -e "$fsckStatusFile" ]]; then
+        rm "$fsckStatusFile"
+    fi
+    if [[ -e "$crystalWorkdir/$fsckId" ]]; then
+        rm -r "${crystalWorkdir:?}/${fsckId:?}"
+    fi
+    trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} while finishing srsync."' ERR
+}
+trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."; finish; exit 1' ERR
+trap finish EXIT
+
 sregNoVerify="true"
 if [[ "$1" == "--no-verify" ]]; then
     sregNoVerify="true"
@@ -52,3 +65,5 @@ fi
 # This NEEDS to skip regular files, because otherwise files that don't exist in the directory will be copied and take up space!
 # rsync -a --ignore-existing --no-i-r "$1" "$2/"
 find "$destinationFindTarget" -type d -empty -exec touch {}/.keep \;
+
+finish
