new version

diff --git a/scripts/sstream-precache b/scripts/sstream-precache
--- a/scripts/sstream-precache
+++ b/scripts/sstream-precache
@@ -10,9 +10,9 @@ while [[ ! -z $1 ]]; do
     if [ -f "$fileToStash" ]; then
         smallify-stream --verbose < "$fileToStash"
     else
-        sstream-dircache "$fileToStash"
+        sstream-dircache "$fileToStash" || warn "Failed precaching $fileToStash!"
     fi
-    echo "Done precaching $fileToStash."
+    echo "Done precaching $fileToStash." || warn "Failed precaching $fileToStash!"
     shift
 done
 printf "\033c"
